%% MBC_Parameters

OBSERV_Parameters_BusDef = BusParamDef("OBSERV_Parameters","Description goes here");

p_LUT_TDiff_Deadtime_D_s    = [7.9  ,   6.88];
p_LUT_TDiff_HV_rpm          = [1400 ,   2400];

p_STCL_EMP_LUT_head_kPa     =   20:10:180;
p_STCL_EMP_LUT_omega_rpm    =   [   2000,   2500,   3000,   3500,   4000,   4200];
p_STCL_EMP_LUT_flow_lpm     =   [   183.92  253.16  0       0       0       0;
                                    156.9   234.36  301.84  0       0       0;
                                    84.68   213.28  287.77  350.94  0       0;
                                    0       182.81  270.44  337.86  389.8   401.65;
                                    0       132.3   251.49  325.49  384.7   396.03;
                                    0       0       225.01  311.79  376.62  390.43;
                                    0       0       193.15  294.54  365.48  384.83; 
                                    0       0       124.32  274.51  355.23  378.89;
                                    0       0       0       251.27  344.01  368.15;
                                    0       0       0       221.42  329.16  356.01;
                                    0       0       0       169.23  308.99  343.2;
                                    0       0       0       0       287.5   326.95;
                                    0       0       0       0       264.34  309.81;
                                    0       0       0       0       229.28  286.75;
                                    0       0       0       0       166.04  260.3;
                                    0       0       0       0       0       217.35;
                                    0       0       0       0       0       0];

p_STCL_dp_Coeffs_bar        =   [   0.0,    0.477,  6.5e-3];

busElements = [ ... 
    % signal name                           %dim    %datatype   % sample time   %    
    % TSens_CLSTi
    BusSignalParamDef('p_CLSti_PT1000_Dynamic_k'         ,   0.14    , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CLSti_PT1000_ObservMargin_T_K'  ,   0       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CLSti_PT1000_Observ_P'          ,   1.5     , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CLSti_PT1000_Observ_I'          ,   0.5     , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    % TSens_CLSTo
    BusSignalParamDef('p_CLSto_PT1000_Dynamic_k'         ,   0.14    , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CLSto_PT1000_ObservMargin_T_K'  ,   0       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CLSto_PT1000_Observ_P'          ,   1.5     , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CLSto_PT1000_Observ_I'          ,   1       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    % TSens_TCVi
    BusSignalParamDef('p_TCVi_PT1000_Dynamic_k'          ,   0.14    , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_TCVi_PT1000_ObservMargin_T_K'   ,   0       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_TCVi_PT1000_Observ_P'           ,   1.5     , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_TCVi_PT1000_Observ_I'           ,   1       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    % TSens_EACi
    BusSignalParamDef('p_EACi_PT1000_Dynamic_k'          ,   1       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EACi_PT1000_ObservMargin_T_K'   ,   1       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EACi_PT1000_Observ_P'           ,   1       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EACi_PT1000_Observ_I'           ,   1       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    % TSens_CHUi    
    BusSignalParamDef('p_CHUi_PT1000_Dynamic_k'          ,   1       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CHUi_PT1000_ObservMargin_T_K'   ,   1       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CHUi_PT1000_Observ_P'           ,   1       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CHUi_PT1000_Observ_I'           ,   1       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    % TSens_CSTi
    BusSignalParamDef('p_CSTi_PT1000_Dynamic_k'          ,   1       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CSTi_PT1000_ObservMargin_T_K'   ,   1       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CSTi_PT1000_Observ_P'           ,   1       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CSTi_PT1000_Observ_I'           ,   1       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    % TSens_CSTo
    BusSignalParamDef('p_CSTo_PT1000_Dynamic_k'          ,   1       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CSTo_PT1000_ObservMargin_T_K'   ,   1       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CSTo_PT1000_Observ_P'           ,   1       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CSTo_PT1000_Observ_I'           ,   1       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
     % TSens_ASVi
    BusSignalParamDef('p_ASVi_PT1000_Dynamic_k'          ,   1       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ASVi_PT1000_ObservMargin_T_K'   ,   1       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ASVi_PT1000_Observ_P'           ,   1       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ASVi_PT1000_Observ_I'           ,   1       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
     % TSens_Ambt
    BusSignalParamDef('p_Ambt_PT1000_Dynamic_k'          ,   1       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Ambt_PT1000_ObservMargin_T_K'   ,   1       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Ambt_PT1000_Observ_P'           ,   1       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Ambt_PT1000_Observ_I'           ,   1       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    % TSens_TDiff_
    BusSignalParamDef('p_STCL_TDiff_Deadtime_D_s'        ,   1       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_TDiff_EstDeadtime_bool'    ,   1       , 1,    'boolean',  -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_TDiff_UseObserved_bool'    ,   1       , 1,    'boolean',  -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_LUT_TDiff_Deadtime_D_s'    ,   p_LUT_TDiff_Deadtime_D_s   , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    's',     '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_LUT_TDiff_TCP_rpm'         ,   p_LUT_TDiff_HV_rpm         , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'rpm',   '', {STREAM_LVL.Release, 1});...
    % EMP TCP
    BusSignalParamDef('p_STCL_EMP_LUT_head_kPa'          ,   p_STCL_EMP_LUT_head_kPa    , 17,       'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'kPA',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_EMP_LUT_omega_rpm'         ,   p_STCL_EMP_LUT_omega_rpm   , 6,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'kPA',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_EMP_LUT_flow_lpm'          ,   p_STCL_EMP_LUT_flow_lpm    , [6, 17],  'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'kPA',   '', {STREAM_LVL.Release, 1});...
    % STCL dp
    BusSignalParamDef('p_STCL_dp_Coeffs_bar'             ,   p_STCL_dp_Coeffs_bar       , 3,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'mbar',  '', {STREAM_LVL.Release, 1});...
    ];  

OBSERV_Parameters_BusDef.AssignBusElements(busElements);

%%
MBC_Parameters_BusDef = BusParamDef("MBC_Parameters","Description goes here");

OBSERV_Parameters_BusDef.AddMetaData({STREAM_LVL.Release, 1});

MBC_Parameters_BusDef.AssignBusElements(OBSERV_Parameters_BusDef);


%% clear working variables

clear p_LUT_TDiff_Deadtime_D_s p_LUT_TDiff_HV_rpm
clear p_STCL_EMP_LUT_head_kPa p_STCL_EMP_LUT_omega_rpm p_STCL_EMP_LUT_flow_lpm
clear p_STCL_dp_Coeffs_bar

clear busElements
clear busName
