flagCheckNameLength = true;

%% GEN_Parameters


GEN_Parameters_BusDef = BusParamDef("GEN_Parameters", "Description goes here");

p_StCurSlpeLUT_I_A              =   [  0  19  20  300  301  400  401  600];
p_StCurSlpeLUT_MaxIncr_I_t_A_s  =   [100 100  10   10   10   10    5    5];
p_StCurSlpeLUT_MaxDecr_I_t_A_s  =   [-20 -20  -20  -20  -5  -5  -5  -5];

p_StCurr_UIDiag_I_A             =   [0    25    50   100  150  200  250  300  350 400];
p_StCurr_UIDiag_UCell_V         =   [0.98  0.88  0.83  0.78 0.76 0.73 0.71 0.69 0.67 0.65];

p_TDer_LUT_CLSti_degC           =   [0 40 45 55 74 75 76 77 78 79 80 82]; 
p_TDer_LUT_dT_K                 =   [0 6 8 10 12 14 18]; 
p_TDer_LUT_Iallowed_A           =   [75 75  75  75  75  75  45;
                                     75 75  75  75  75  75  45;
                                     420 420 420 420 420 420 300;
                                     420 420 420 420 420 420 300;
                                     420 420 420 420 420 300   0;
                                     420 420 420 420 420 200   0;
                                     420 420 420 420 420   0   0;
                                     420 420 420 420 300   0   0;
                                     420 420 410 420   0   0   0;
                                     420 420 400 300   0   0   0;
                                     410 410 200   0   0   0   0;
                                     200 200   0   0   0   0   0]';
p_HXDer_LUT_T_CSti_degC         =   [  0  40  45  55  74  75  80  85  86  87  88  89  90];
p_HXDer_LUT_Iallowed_A          =   [420 420 420 420 420 420 420 420 420 420 380 350 350];

p_Temperature_0_100_degC= [0     10     20      30  40      50  60   70    80    90    100];
p_Water_LUT_cp_JKgK     = [4.217 4.192 4.182 4.178 4.179 4.181 4.185 4.190 4.196 4.205 4.216];
p_Water_LUT_rho_Kgl     = [0.998 0.999 0.998 0.995 0.992 0.988 0.983 0.977 0.971 0.965 0.958];
p_Gysantin_LUT_cp_JKgK  = [2.34  2.39  2.45  2.5   2.55  2.60  2.645 2.69  2.73  2.77  2.80];
p_Gysantin_LUT_rho_Kgl  = [1.135 1.128 1.122 1.115 1.107 1.100 1.094 1.086 1.078 1.072 1.065];

busElements = [ ... 
    % signal name                   %dim    %datatype   % sample time   %    
    BusSignalParamDef('p_ManualMode_PIN'                 ,   1234                            , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',          '', {STREAM_LVL.Debug, 1});...
    BusSignalParamDef('p_NumberOfCells'                  ,   455                             , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',          '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_FaradaysConstant_AsPerMol'      ,   96485.3399                      , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'As/mol',    '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_MolMass_O2_gPerMol'             ,   31.998                          , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'g/mol',     '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Air_O2_Share_Mass_percent'      ,   23.133                          , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'percent',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Air_O2_Share_Vol_percent'       ,   20.946                          , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'percent',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Air_cp_JKgK'                    ,   1006                            , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'J/Kg/K',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Air_isentropicExp'              ,   1.4                             , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Water_cp_JKgK'                  ,   4182                            , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'J/Kg/K',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Gysantin_cp_JKgK'               ,   2450                            , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'J/Kg/K',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Water_rho_Kgl'                  ,   0.998                           , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'Kg/l',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Gysantin_rho_Kgl'               ,   1.122                           , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'Kg/l',   '', {STREAM_LVL.Release, 1});...
    
    BusSignalParamDef('p_Temperature_0_100_degC'         ,   p_Temperature_0_100_degC        ,11,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'degC',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Water_LUT_cp_JKgK'              ,   p_Water_LUT_cp_JKgK             ,11,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'J/Kg/K',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Water_LUT_rho_Kgl'              ,   p_Water_LUT_rho_Kgl             ,11,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'Kg/l',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Gysantin_LUT_cp_JKgK'           ,   p_Gysantin_LUT_cp_JKgK          ,11,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'J/Kg/K',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Gysantin_LUT_rho_Kgl'           ,   p_Gysantin_LUT_rho_Kgl          ,11,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'Kg/l',   '', {STREAM_LVL.Release, 1});...    
    
    BusSignalParamDef('p_Coolant_H2O_Share'              ,   0.50                            , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'J/Kg/K',   '', {STREAM_LVL.Release, 1});...
    %% Current Request Parameters
    BusSignalParamDef('p_StCurr_Max_I_A'                 ,   420                             , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_StCurr_Min_I_A'                 ,   0                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_StCurr_FastOffLoad_Min_I_A'     ,   0                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    's',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_StCurr_FastOffSubsys_Min_I_A'   ,   20                              , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    's',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_StCurr_RampOffLoad_Min_I_A'     ,   2                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    's',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_StCurr_RampOffSubsys_Min_I_A'   ,   50                              , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    's',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_StCurr_RampOnLoad_Max_I_A'      ,   20                              , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    's',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_StCurr_RampOnSubsys_Max_I_A'    ,   45                              , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    's',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_StCurSlpeLUT_I_A'               ,   p_StCurSlpeLUT_I_A              , 8,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A/s',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_StCurSlpeLUT_MaxIncr_I_t_A_s'   ,   p_StCurSlpeLUT_MaxIncr_I_t_A_s  , 8,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A/s',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_StCurSlpeLUT_MaxDecr_I_t_A_s'   ,   p_StCurSlpeLUT_MaxDecr_I_t_A_s  , 8,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A/s',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_StCurSlpe_MaxRunUpIncr_I_t_A_s' ,   2                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A/s',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_StCurSlpe_MaxRunUpDecr_I_t_A_s' ,   -3                              , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A/s',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_StCurr_ErrorMargin_I_A'         ,   0.4                             , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A/s',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_StCurr_DynUpDown_D_t_s'         ,   5.0                             , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    's',   '', {STREAM_LVL.Release, 1});...
    
    %UI Diagram
    BusSignalParamDef('p_StCurr_OCV_U_V'	            ,   1.23                            , 1,   'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'V',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_StCurr_UIDiag_I_A'	            ,   p_StCurr_UIDiag_I_A             , 10,   'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A/s',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_StCurr_UIDiag_UCell_V'          ,   p_StCurr_UIDiag_UCell_V         , 10,   'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A/s',   '', {STREAM_LVL.Release, 1});...
    %% Temperature Derating
    BusSignalParamDef('p_TDer_StCurSlpe_MaxIncr_I_t_A_s' ,   2                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A/s',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_TDer_StCurSlpe_MaxDecr_I_t_A_s' ,   -20                             , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A/s',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_TDer_Debouncing_s'              ,   0.01                            , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A/s',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_TDer_LUT_CLSti_degC'            ,   p_TDer_LUT_CLSti_degC           , 12,   'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'degC',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_TDer_LUT_dT_K'                  ,   p_TDer_LUT_dT_K                 , 7,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'K',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_TDer_LUT_Iallowed_A'            ,   p_TDer_LUT_Iallowed_A           , [12,7],   'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_HXDer_LUT_T_CSti_degC'          ,   p_HXDer_LUT_T_CSti_degC         , size(p_HXDer_LUT_T_CSti_degC,2),   'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_HXDer_LUT_Iallowed_A'           ,   p_HXDer_LUT_Iallowed_A          , size(p_HXDer_LUT_Iallowed_A,2),   'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_TDer_Override_CurAllowed_bool'  ,   false                           , 1,    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    'bool',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_TDer_Override_CurAllowed_I_A'   ,   420                             , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A',   '', {STREAM_LVL.Release, 1});...
    %% Controller Parameters
    BusSignalParamDef('p_CurrentRequestCycleTime_s'      ,   0.01                            , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    's',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_StCurr_MaxDevReq_I_A'           ,   500                             , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',   '', {STREAM_LVL.Release, 1});...
    %% Surge Derating
    BusSignalParamDef('p_StCurr_SurgeDer_factor'         ,   0.98                            , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A',   '', {STREAM_LVL.Release, 1});...
    
    %% Valve Self-testing
    BusSignalParamDef('p_VlvSelfTesting_OES_TO_s'        ,   10                              , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A',   '', {STREAM_LVL.Debug, 1});...
    BusSignalParamDef('p_VlvSelfTest_OES_Tol_per'        ,   5                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A',   '', {STREAM_LVL.Debug, 1});...
    BusSignalParamDef('p_VlvSelfTesting_TCV_TO_s'        ,   10                              , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A',   '', {STREAM_LVL.Debug, 1});...
    BusSignalParamDef('p_VlvSelfTest_TCV_Tol_per'        ,   5                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A',   '', {STREAM_LVL.Debug, 1});...
    ];

GEN_Parameters_BusDef.AssignBusElements(busElements);

%% clear working variables

clear busElements
clear busName
