
%% ECooling_CtrlParam

ECCL_Parameters_BusDef = BusParamDef("ECCL_Parameters", "Description goes here");


busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %    
    BusSignalParamDef('p_ECCL_SP_Off_omega_rpm'          ,   0       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ECCL_SP_Idle_omega_rpm'         ,   3000    , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ECCL_SP_constRpmMax_omega_rpm'  ,   3000    , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    % thesholds and limits
    BusSignalParamDef('p_ECCL_TurningOff_TO_D_s'         ,   100     , 1,    'single',   -1,     'real', 'Sample','Fixed',   [],     [],     's',     '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ECCL_TurningOn_TO_D_s'          ,   100     , 1,    'single',   -1,     'real', 'Sample','Fixed',   [],     [],     's',     '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ECCL_Off_MaxPressure_TH_p_bara' ,   1.1     , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ECCL_On_MinPressure_TH_p_bara'  ,   1.2     , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ECCL_On_MinSpeed_TH_omega_rpm'  ,   2000    , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ECCL_Off_MaxSpeed_TH_omega_rpm' ,   100     , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ECCL_min_rpm'                   ,   1000    , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ECCL_max_rpm'                   ,   3500    , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_ECCL_Shutdown_AfterCooling_D_s' , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    's',  '', {STREAM_LVL.Release, 1});...
    ]; 

ECCL_Parameters_BusDef.AssignBusElements(busElements);


%% clear working variables

clear busElements
clear busName
