flagCheckNameLength = true;

%% EL_Parameters

EL_Parameters_BusDef = BusParamDef("EL_Parameters", "Description goes here");

busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % LV
    BusSignalParamDef('p_LVCONConnected_TH_I_A'          ,   0.05 , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_LVCONConnecting_TO_s'           ,   2   , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    's',  '', {STREAM_LVL.Release, 1});...
    % HVCON
    BusSignalParamDef('p_HVCONBothConnected_D_s'         ,   0.1 , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    's',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_HVCONPrecharge_D_s'             ,   4   , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    's',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_HVCON_Precharge_Current_TH_I_A' ,   0.1 , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A',  '', {STREAM_LVL.Release, 1});...
    % not needed: BusSignalParamDef('p_HVCONPrecharge_Voltage_TH_U_V'                 , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'V',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_HVCONPrecharge_TO_s'            ,   5   , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'V',  '', {STREAM_LVL.Release, 1});...
    % LCON
    BusSignalParamDef('p_LCONPrecharge_D_s'              ,   4   , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    's',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_LCONPrecharge_Current_TH_I_A'   ,   0.1 , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_LCONBothConnected_D_s'          ,   0.1 , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    's',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_LCONPrecharge_TO_s'             ,   5   , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    's',  '', {STREAM_LVL.Release, 1});...  
    BusSignalParamDef('p_LCONDiag_TO_s'                  ,   1   , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    's',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_LCONDiag_Bypass_bool'           ,   1   , 1,    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    % RDIS - Discharge Resistor
    BusSignalParamDef('p_RDIS_SP_On_R_percent'           ,   25  , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    's',  '', {STREAM_LVL.Release, 1});... 
    BusSignalParamDef('p_RDIS_Overheat_TH_T_degC'        ,   125 , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    's',  '', {STREAM_LVL.Release, 1});... 
    BusSignalParamDef('p_RDIS_On_TO_s'                   ,   20  , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    's',  '', {STREAM_LVL.Release, 1});... 
    ];

EL_Parameters_BusDef.AssignBusElements(busElements);

%% clear working variables

clear busElements
clear busName
