flagCheckNameLength = true;

%% ARECI_Parameters

% initialize bus definition object
ARECI_Parameters_BusDef = BusParamDef("ARECI_Parameters", "Description goes here");

p_ARECI_SP_LUT_I_A              = [0      50      100     150     200     250     300     350     400     425     450     475     500];
p_ARECI_SP_LUT_omega_rpm        = [4500   4500    4500    4500    4500    4500    4500    4500    4500    4700    4700    4700    4700];

p_ARECI_V3_SP_LUT_I_A           = [0      50      100       150     200     250     300     350     400     425     450     475     500];
p_ARECI_V3_SP_LUT_omega_rpm     = [8000   9000    10000    12000    14000    16000    18000    20000    20000    20000    20000    20000    20000];

busElements = [ ... 
    % signal name                           %value %dim    %datatype   % sample time   %
    %
    % Setpoints
    BusSignalParamDef('p_ARECI_SP_Off_omega_rpm'             , 0                         ,   1,  'single',               -1, 'real', 'Sample','Fixed',   [],     [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ARECI_SP_Idle_omega_rpm'            , 3500                      ,   1,  'single',               -1, 'real', 'Sample','Fixed',   [],     [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ARECI_SP_Startup_omega_rpm'         , 3500                      ,   1,  'single',               -1, 'real', 'Sample','Fixed',   [],     [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ARECI_SP_ConstRpmLow_omega_rpm'     , 3500                      ,   1,  'single',               -1, 'real', 'Sample','Fixed',   [],     [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ARECI_SP_ConstRpmMid_omega_rpm'     , 3500                      ,   1,  'single',               -1, 'real', 'Sample','Fixed',   [],     [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ARECI_SP_ConstRpmHi_omega_rpm'      , 4700                      ,   1,  'single',               -1, 'real', 'Sample','Fixed',   [],     [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ARECI_SP_LUT_I_A'                   , p_ARECI_SP_LUT_I_A        ,  13,  'single',               -1, 'real', 'Sample','Fixed',   [],     [],    'A',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ARECI_SP_LUT_omega_rpm'             , p_ARECI_SP_LUT_omega_rpm  ,  13,  'single',               -1, 'real', 'Sample','Fixed',   [],     [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    % thresholds and timings
    BusSignalParamDef('p_ARECI_CurrentDecreaseDelay_D_s'     , 10                        ,   1,  'single',              -1, 'real', 'Sample','Fixed',   [],     [],     's',     '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ARECI_TurningOff_TO_D_s'            , 3                         ,   1,  'single',              -1, 'real', 'Sample','Fixed',   [],     [],     's',     '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ARECI_TurningOn_TO_D_s'             , 3                         ,   1,  'single',              -1, 'real', 'Sample','Fixed',   [],     [],     's',     '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ARECI_OFF_MaxSpd_TH_omega_rpm'      , 100                       ,   1,  'single',              -1, 'real', 'Sample','Fixed',   [],     [],     'rpm',   '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ARECI_ON_MinSpd_TH_omega_rpm'       , 1000                      ,   1,  'single',              -1, 'real', 'Sample','Fixed',   [],     [],     'rpm',   '', {STREAM_LVL.Release, 1});...

    BusSignalParamDef('p_ARECI_V3_SP_Off_omega_rpm'             , 0                         ,   1,  'single',               -1, 'real', 'Sample','Fixed',   [],     [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ARECI_V3_SP_Idle_omega_rpm'            , 6000                      ,   1,  'single',               -1, 'real', 'Sample','Fixed',   [],     [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ARECI_V3_SP_Startup_omega_rpm'         , 6000                      ,   1,  'single',               -1, 'real', 'Sample','Fixed',   [],     [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ARECI_V3_SP_LUT_I_A'                   , p_ARECI_V3_SP_LUT_I_A        ,  13,  'single',               -1, 'real', 'Sample','Fixed',   [],     [],    'A',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ARECI_V3_SP_LUT_omega_rpm'             , p_ARECI_V3_SP_LUT_omega_rpm  ,  13,  'single',               -1, 'real', 'Sample','Fixed',   [],     [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ARECI_V3_IncreaseRate_rpm_s'           , 4000                        ,   1,  'single',              -1, 'real', 'Sample','Fixed',   [],     [],     's',     '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ARECI_V3_DecreaseRate_rpm_s'           , -8000                        ,   1,  'single',              -1, 'real', 'Sample','Fixed',   [],     [],     's',     '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_ARECI_Shutdown_AfterRun_D_s'       , 1,    'single',              -1, 'real', 'Sample','Fixed',   [],     [],     's',     '', {STREAM_LVL.Release, 1});...
    ];

clear p_ARECI_SP_LUT_I_A p_ARECI_SP_LUT_omega_rpm

% assign defined bus signals to bus
ARECI_Parameters_BusDef.AssignBusElements(busElements);

%declareBusAndInitStructAndMeta(busName, busElements, flagCheckNameLength, 'ParameterBus');

%% APRES_Parameters


APRES_Parameters_BusDef = BusParamDef("APRES_Parameters", "Description goes here");


p_APRES_DC_LUT_pDiff_ANAmb_p_bar    =   [0      0.3     0.4     0.5     0.6     0.7     0.8     0.9     1.0     1.1     1.2     1.3     1.4     1.5     1.6     1.7     1.8];
p_APRES_DC_LUT_APV_Delay_s          =   [0.00   0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00];
p_APRES_DC_LUT_ADV_Delay_s          =   [0.00   0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00];
p_APRES_DC_LUT_APV_Hold_per         =   [100    100     100     100     100     100     100     100     100     100     100     100     100     100     100     100     100];
p_APRES_DC_LUT_ADV_Hold_per         =   [100    100     100     100     100     100     100     100     100     100     100     100     100     100     100     100     100];
p_APRES_DC_LUT_APV_Gain_pos_per     =   [0      0       1       1       1       0       0.5     0.5     0.5     0.5     0.5     3         5       7       7       7       7];
p_APRES_DC_LUT_ADV_Gain_pos_per     =   [0      0       3       3       3       2       3       3       3.25    3.5     4       8        10      10      10      10      10];

p_APRES_PID_LUT_I_A                 =   [0      50     100     150     200     250     300     350     400     425     450     475     500];
p_APRES_PID_LUT_PGain               =   [200   200     200     200     200     250     300     350     400     400     400     400     400];


busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % Setpoints
    BusSignalParamDef('p_APRES_SP_Off_pos_percent'           , 0     ,   1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_SP_PresCtrl_p_bar'            , 1.3   ,1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_SP_DiffPresCtrl_dp_bar'       , 0.2   ,  1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_SP_EMShutdown_p_bara'         , 1     ,  1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    % Setpoint Filter
    BusSignalParamDef('p_APRES_SP_ActivateCatPresFilter'     , 1,   1,    'boolean',   -1,             'real', 'Sample','Fixed',    [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_CatPresFilter_T_s'            , 0.5,   1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    % Controller Parameters
    BusSignalParamDef('p_APRES_PID_DiffPCtrl_P'              , 80,   1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_PID_DiffPCtrl_I'              , 13,   1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_PID_DiffPCtrl_D'              ,  0,   1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_PID_DiffPCtrl_N'              ,  1,   1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_PID_PresCtrl_P'               , 30,   1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_PID_PresCtrl_I'               , 13,   1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_PID_PresCtrl_D'               ,  0,   1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_PID_PresCtrl_N'               ,  1,   1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_PID_UpperLim_pos_per'         , 100,   1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_PID_LowerLim_pos_per'         , 0,   1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_PID_Offset_pos_per'           , 0,   1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    % Gain Scheduling
    BusSignalParamDef('p_APRES_PID_LUT_enable'               , 1,   1,    'boolean',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_PID_LUT_I_A'                  , p_APRES_PID_LUT_I_A,     13,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_PID_LUT_PGain'                , p_APRES_PID_LUT_PGain,   13,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    % APRV Feed-Forward Controller Current
    BusSignalParamDef('p_APRES_FFCurr_LUT_APRV_pos_per'      ,  [35   36  37  39  42  44.9    50.3  50.7 	53.5    56.9    60.4    63.4    66.1    66.1],   14,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_FFCurr_LUT_I_A'               ,  [0    10  20  30  40  50      75  100   150     200     250     300     350     400],   14,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_FFCurr_Gain'                  ,  1,   1,        'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_FFCurr_FilterFreq_Hz'         ,  100,   1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    % Purge Drain Distrubance Control Parameters
    BusSignalParamDef('p_APRES_DC_APV_Delay_s'               , 0,   1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   's',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_DC_ADV_Delay_s'               , 0,   1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   's',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_DC_APV_Gain_percent'          , 12,   1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '%',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_DC_ADV_Gain_percent'          , 12,                               1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '%',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_DC_APV_Hold_percent'          , 100,                              1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '%',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_DC_ADV_Hold_percent'          , 100,                              1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '%',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_DC_LUT_pDiff_ANAmb_p_bar'     , p_APRES_DC_LUT_pDiff_ANAmb_p_bar, 17,  'single',   -1,              'real', 'Sample','Fixed',    [],  [],   'bar',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_DC_LUT_APV_Delay_s'           , p_APRES_DC_LUT_APV_Delay_s,       17,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   's',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_DC_LUT_ADV_Delay_s'           , p_APRES_DC_LUT_ADV_Delay_s,       17,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   's',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_DC_LUT_APV_Hold_per'          , p_APRES_DC_LUT_APV_Hold_per,      17,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '%',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_DC_LUT_ADV_Hold_per'          , p_APRES_DC_LUT_ADV_Hold_per,      17,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '%',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_DC_LUT_APV_Gain_pos_per'      , p_APRES_DC_LUT_APV_Gain_pos_per,  17,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '%',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_DC_LUT_ADV_Gain_pos_per'      , p_APRES_DC_LUT_ADV_Gain_pos_per,  17,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '%',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRES_DC_Gain'                      , 1 ,                               1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});... 

        
    % Anode Pressure Regulation Valve Characteristics
    %BusSignalParamDef('p_APRV_ValveCurrnLUT_I_mA'            ,       2,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_APRV_ValveCurrLUT_pos_per'          ,       2,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    % Parameters resolving issues
    %
    % not yet used!!
    BusSignalParamDef('p_APRES_St3_ControlVariant'               , 1, 1,  'single', -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_St3_Use2Valves'               , 0, 1,  'boolean', -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...

    BusSignalParamDef('p_APRV_DecrAPRViPres_TH_p_bara', 0, 1,  'single', -1,             'real', 'Sample','Fixed',    [],  [],   '',  'The system decreases the APRVi pressure until this pressure is reached', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRV_CompMemDiffPres_TH_p_bara', 0, 1, 'single', -1,             'real', 'Sample','Fixed',    [],  [],   '',  'The system compensates the Membrane Difference Pressure until this pressure for p_ASTi is reached', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRV_OpenAndHold_TH_p_bar',         0 ,  1,        'single', -1,             'real', 'Sample','Fixed',    [],  [],   '',  'With this value the beginning of a pressure equalization is recgnonized --> then the valve is hold in its position', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRV_OpenSpd_percentPerSecond', 0,  1,      'single', -1,             'real', 'Sample','Fixed',    [],  [],   '',  'This value describes how fast the valve is opened while resolving issues', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRV_ResIssues_StrtPos_pos_per',0 , 1,  'single', -1,             'real', 'Sample','Fixed',    [],  [],   '',  'This value describes how fast the valve is opened while resolving issues', {STREAM_LVL.Release, 1}); ...

    BusSignalParamDef('p_APRES_FFCurr_LUT_APRV2_pos_per', [0      0       4       10       16      20      25      25      37      39      41      44      44      45],  14, 'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_FFCurr_LUT_APRV3_pos_per',   0.7*[0      0       0       0       0       0       0       0       0      0      0      0      0      0],   14,'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    
    % Bosch Valve
    BusSignalParamDef('p_APRES_APRV3_PID_P'                  ,0      , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ... 
    BusSignalParamDef('p_APRES_APRV3_PID_I'                  ,0      , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ... 
    BusSignalParamDef('p_APRES_APRV3_PID_D'                  ,0      , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ... 
    BusSignalParamDef('p_APRES_APRV3_PID_TI'                 ,0      , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ... 
    BusSignalParamDef('p_APRES_APRV3_PID_TD'                 ,0      , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ... 
    BusSignalParamDef('p_APRES_APRV3_PID_UpLim_pos_per'      ,35     , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ... 
    BusSignalParamDef('p_APRES_APRV3_PID_LowLim_pos_per'     ,0      , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ... 
    BusSignalParamDef('p_APRES_APRV3_PID_Offset_pos_per'     ,0     , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ... 
    BusSignalParamDef('p_APRES_APRV3_PID_DisTime_t_s'        ,0      , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...   
    % 1st MS Valve
    BusSignalParamDef('p_APRES_APRV1_PID_P'                  ,  50  , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ... % 500
    BusSignalParamDef('p_APRES_APRV1_PID_I'                  ,  0.5    , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ... % 1
    BusSignalParamDef('p_APRES_APRV1_PID_D'                  ,  0    , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ... % 3
    BusSignalParamDef('p_APRES_APRV1_PID_TI'                 ,  0    , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_APRV1_PID_TD'                 , 0     , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_APRV1_PID_UpLim_pos_per'      , 100    , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...   % [percent]
    BusSignalParamDef('p_APRES_APRV1_PID_LowLim_pos_per'     ,  0    , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...        % [percent] %TODO: could be increased to a higher value since we don't see any action below 35 or something
    BusSignalParamDef('p_APRES_APRV1_PID_Offset_pos_per'     , 0    , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...         % [percent]
    BusSignalParamDef('p_APRES_APRV1_PID_DisTime_t_s'        , 0     , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    % 2nd MS Valve
    BusSignalParamDef('p_APRES_APRV2_PID_P'                  , 0     , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_APRV2_PID_I'                  , 3     , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_APRV2_PID_D'                  , 0     , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_APRV2_PID_TI'                 , 0     , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_APRV2_PID_TD'                 , 0     , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_APRV2_PID_UpLim_pos_per'      , 100   , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_APRV2_PID_LowLim_pos_per'     , 0     , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_APRV2_PID_Offset_pos_per'     , 0    , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_APRV2_PID_DisTime_t_s'        , 0     , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...

    BusSignalParamDef('p_APRES_APRV0_PID_P'                  , 0     , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ... %500
    BusSignalParamDef('p_APRES_APRV0_PID_I'                  , 0     , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...  % 1
    BusSignalParamDef('p_APRES_APRV0_PID_D'                  , 0     , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ... % 3
    BusSignalParamDef('p_APRES_APRV0_PID_TI'                 , 0     , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_APRV0_PID_TD'                 , 0     , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_APRV0_PID_UpLim_pos_per'      , 100   , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_APRV0_PID_LowLim_pos_per'     , 0     , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_APRV0_PID_Offset_pos_per'     , 0    , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_APRV0_PID_DisTime_t_s'        , 0     , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...

    BusSignalParamDef('p_APRES_DC_Mode'                      , 0         ,1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_DC_ApplyTime_t_s'             , 1         ,1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_DC_THGainCtrl1_bar'    , [-0.025, 0.010] ,2,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_DC_THGainCtrl2_bar'    , [-0.025, 0.010] ,2,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_DC_GainCtrl1_per'             , [3, -7]   , 2,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_DC_GainCtrl2_per'             , [3, -7]   , 2,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_DC_GainLimit_per'             , 70        , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_DC_PID1_Purge_DisFactor'      , 0         , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  'Results, multiplied with the current purge opening time, as the disable time for the PID control while purge is active', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_DC_PID2_Purge_DisFactor'      , 0         , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  'Results, multiplied with the current purge opening time, as the disable time for the PID control while purge is active', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_DC_PID3_Purge_DisFactor'      , 0         , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  'Results, multiplied with the current purge opening time, as the disable time for the PID control while purge is active', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_DC_PID1_Drain_DisFactor'      , 0         , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  'Results, multiplied with the current drain opening time, as the disable time for the PID control while drain is active', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_DC_PID2_Drain_DisFactor'      , 0         , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  'Results, multiplied with the current drain opening time, as the disable time for the PID control while drain is active', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_DC_PID3_Drain_DisFactor'      , 0         , 1,  'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  'Results, multiplied with the current drain opening time, as the disable time for the PID control while drain is active', {STREAM_LVL.Release, 1}); ...

    BusSignalParamDef('p_APRES_DC_IdxShift'                  , 1         , 1, 'single', -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_DC_Gain_per'                  , 1         , 1, 'single', -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_DC_HoldTime_t_s'              , 1         , 1, 'single', -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...

    BusSignalParamDef('p_APRES_I2_ActivateIntShifting', 1          , 1, 'single',  -1,      'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_I2_ConditionInterval_t_s'    , 2          , 1, 'single', -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_I2_ConditionTH_I_A'           ,2          , 1, 'single', -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_I2_Value_pos_percent'         ,0.05       , 1, 'single', -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_I2_OpPoint_pos_percent'       ,55         , 1, 'single', -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_I2_Hyst_pos_percent'          ,5          , 1, 'single', -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...
    BusSignalParamDef('p_APRES_I2_OvershootDecrease'         ,25         , 1, 'single', -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1}); ...

    ];

clear p_APRES_DC_LUT_pDiff_ANAmb_p_bar p_APRES_DC_LUT_APV_Delay_s p_APRES_DC_LUT_ADV_Delay_s p_APRES_DC_LUT_APV_Hold_per p_APRES_DC_LUT_ADV_Hold_per p_APRES_DC_LUT_APV_Gain_pos_per p_APRES_DC_LUT_ADV_Gain_pos_per

% assign defined bus signals to bus
APRES_Parameters_BusDef.AssignBusElements(busElements);


%% APD_Paramters

APD_Parameters_BusDef = BusParamDef("APD_Parameters", "Description goes here");

p_APD_Run_LUTOpenings_I_A       =   [0      50      100     150     200     250     300     350     400     425     450     475     500];
p_APD_Run_LUT_PurgeOpen_t_s     =   [0.5    0.5     0.5     0.5     0.5     0.5     0.5     0.5     0.5     0.5     0.5     0.5     0.5];
p_APD_Run_LUT_DrainOpen_t_s     =   [2.3    2.3     2.1     2.0     1.5     1.5     1.4     1.8     2.0     2.2     2.0     2.0     2.0];
p_APD_Run_LUT_Drain2Open_t_s     =   [2.3    2.3     2.1     2.0     1.5     1.5     1.4     1.8     2.0     2.2     2.0     2.0     2.0];

p_APD_Run_LUTPeriods_I_s        =   [0      50      100     150     200     250     300     350     400     425     450     475     500];
p_APD_Run_LUT_T_degC            =   [2	    45	    60	    75	    85];
p_APD_Run_LUT_PurgePeriod_t_s  =    [7.0    7.0     6.4     5.9     5.3     4.7     4.1     3.6     3.0     4.0     4.0     4.0     4.0;   % 2
                                     7.0    7.0     6.4     5.9     5.3     4.7     4.1     3.6     3.0     4.0     4.0     4.0     4.0;   % 45
                                     7.0    7.0     6.4     5.9     5.3     4.7     4.1     3.6     3.0     4.0     4.0     4.0     4.0;   % 60   
                                     7.0    7.0     6.4     5.9     5.3     4.7     4.1     3.6     3.0     4.0     4.0     4.0     4.0;   % 75   
                                     7.0    7.0     6.4     5.9     5.3     4.7     4.1     3.6     3.0     4.0     4.0     4.0     4.0]'; % 85     
                                
p_APD_Run_LUT_DrainPeriod_t_s  =    [21.0   18.0    16.6    15.4    14.1    11.5    9.5     8.0     5.0     4.0     4.0     4.0     4.0;  % 2
                                     21.0   18.0    16.6    15.4    14.1    11.5    9.5     8.0     5.0     4.0     4.0     4.0     4.0;   % 45
                                     21.0   18.0    16.6    15.4    14.1    11.5    9.5     8.0     5.0     4.0     4.0     4.0     4.0;   % 60
                                     21.0   18.0    16.6    15.4    14.1    11.5    9.5     8.0     5.0     4.0     4.0     4.0     4.0;   % 75
                                     21.0   18.0    16.6    15.4    14.1    11.5    9.5     8.0     5.0     4.0     4.0     4.0     4.0]'; % 85

p_APD_Run_LUT_Drain2Period_t_s  =    [21.0   18.0    16.6    15.4    14.1    11.5    9.5     8.0     5.0     4.0     4.0     4.0     4.0;  % 2
                                     21.0   18.0    16.6    15.4    14.1    11.5    9.5     8.0     5.0     4.0     4.0     4.0     4.0;   % 45
                                     21.0   18.0    16.6    15.4    14.1    11.5    9.5     8.0     5.0     4.0     4.0     4.0     4.0;   % 60
                                     21.0   18.0    16.6    15.4    14.1    11.5    9.5     8.0     5.0     4.0     4.0     4.0     4.0;   % 75
                                     21.0   18.0    16.6    15.4    14.1    11.5    9.5     8.0     5.0     4.0     4.0     4.0     4.0]'; % 85


busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % purge
    BusSignalParamDef('p_APD_Off_PurgeOpen_t_s'          , 0, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_Off_PurgePeriod_t_s'        , 0, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_Off_DrainOpen_t_s'          , 0, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_Off_DrainPeriod_t_s'        , 0, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_Off_Drain2Open_t_s'          , 0, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_Off_Drain2Period_t_s'        , 0, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    % flush
    BusSignalParamDef('p_APD_Flush_PurgeOpen_t_s'        , 0.1, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_Flush_PurgePeriod_t_s'      , 1, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_Flush_DrainOpen_t_s'        , 0.2, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_Flush_DrainPeriod_t_s'      , 5.2, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_Flush_Drain2Open_t_s'        , 0.2, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_Flush_Drain2Period_t_s'      , 5.2, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    % startup
    BusSignalParamDef('p_APD_Startup_PurgeOpen_t_s'      , 0.1, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_Startup_PurgePeriod_t_s'    , 2.1, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_Startup_DrainOpen_t_s'      , 0.1, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_Startup_DrainPeriod_t_s'    , 20.1, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_Startup_Drain2Open_t_s'      , 0.1, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_Startup_Drain2Period_t_s'    , 20.1, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    % run 
    BusSignalParamDef('p_APD_Run_LUTOpenings_I_S'        ,p_APD_Run_LUTOpenings_I_A , 13,    'single',    -1,             'real', 'Sample','Fixed',    [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_Run_LUT_PurgeOpen_t_s'      ,p_APD_Run_LUT_PurgeOpen_t_s , 13,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_Run_LUT_DrainOpen_t_s'      ,p_APD_Run_LUT_DrainOpen_t_s , 13,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_Run_LUT_Drain2Open_t_s'      ,p_APD_Run_LUT_Drain2Open_t_s , 13,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    %
    BusSignalParamDef('p_APD_Run_LUTPeriods_I_s'         ,p_APD_Run_LUTPeriods_I_s , 13,    'single',    -1,             'real', 'Sample','Fixed',    [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_Run_LUT_T_degC'             ,p_APD_Run_LUT_T_degC , 5,    'single',    -1,             'real', 'Sample','Fixed',    [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_Run_LUT_PurgePeriod_t_s'    ,p_APD_Run_LUT_PurgePeriod_t_s , [5 ,13],    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_Run_LUT_DrainPeriod_t_s'    ,p_APD_Run_LUT_DrainPeriod_t_s , [5 ,13],    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_Run_LUT_Drain2Period_t_s'    ,p_APD_Run_LUT_Drain2Period_t_s , [5 ,13],    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    % current based run
    BusSignalParamDef('p_APD_IntegratedCurrDrain_TH_As'  , 0.5, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_IntegratedCurrPurge_TH_As'  , 0.5, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    % shutdown 
    BusSignalParamDef('p_APD_Shutdown_PurgeOpen_t_s'     , 0.1, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_Shutdown_PurgePeriod_t_s'   , 2.1, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_Shutdown_DrainOpen_t_s'     , 0.1, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_Shutdown_DrainPeriod_t_s'   , 20.1, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});... 
    BusSignalParamDef('p_APD_Shutdown_Drain2Open_t_s'     , 0.1, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_Shutdown_Drain2Period_t_s'   , 20.1, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});... 
    % dry cathode
    BusSignalParamDef('p_APD_DryCat_PurgeOpen_t_s'   , 0.1 , 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_DryCat_PurgePeriod_t_s' , 2.1, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_DryCat_DrainOpen_t_s'   , 0.1, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_DryCat_DrainPeriod_t_s' , 20.1,  1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_DryCat_Drain2Open_t_s'   , 0.1, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_DryCat_Drain2Period_t_s' , 20.1,  1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...

    BusSignalParamDef('p_APD_EventStartup_Sequence_D_s'  , [1 1 1 1 0.5 1 0.5], 7,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  'Define opening and wait times between purge and drain actions', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_EventPurge_Sequence_D_s'    , 0.5, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  'Defines opening time of purge valve during single purge event', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_EventDrain_Sequence_D_s'    , 0.5, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  'Defines opening time of drain valve during single drain event', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_EventPurgeExt_Sequence_D_s' , 0.5, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  'Defines opening time of purge valve during externally triggered purge event', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_EventDrainExt_Sequence_D_s' , 0.5, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  'Defines opening time of drain valve during externally triggered drain event', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_WaitTimeAfterEvent_D_s'     , 0.5, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  'Defines the wait time before reentering cyclic mode after a APV event is done', {STREAM_LVL.Release, 1});...

    % em shutdown
    %BusSignalParamDef('p_APD_EMShutdown_PurgeOpen_t_s'   , 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_APD_EMShutdown_PurgePeriod_t_s' , 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_APD_EMShutdown_DrainOpen_t_s'   , 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_APD_EMShutdown_DrainPeriod_t_s' , 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    % parameters
    BusSignalParamDef('p_APD_PurgeClosing_D_s'           , 0.02, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_DrainClosing_D_s'           , 0.02, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APV_DelayPurge_D_s'             , 0.1, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   's',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ADV_DelayDrain_D_s'             , 0.1, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   's',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_UseBothValves_bool'         , 0, 1,      'boolean',   -1,             'real', 'Sample','Fixed',    [],  [],   's',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APD_TimeBetweenDrains_D_s'      , 1, 1,    'single',   -1,             'real', 'Sample','Fixed',    [],  [],   's',  '', {STREAM_LVL.Release, 1});...
    ];

clear p_APD_Run_LUTOpenings_I_s p_APD_Run_LUT_PurgeOpen_t_s p_APD_Run_LUT_DrainOpen_t_s p_APD_Run_LUTPeriods_I_s p_APD_Run_LUT_T_degC p_APD_Run_LUT_PurgePeriod_t_s p_APD_Run_LUT_DrainPeriod_t_s

% assign defined bus signals to bus
APD_Parameters_BusDef.AssignBusElements(busElements)

%% AN_Parameters
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

AN_Parameters_BusDef = BusParamDef("AN_Parameters", "Description goes here");

ARECI_Parameters_BusDef.AddMetaData({STREAM_LVL.Release, 1});
APRES_Parameters_BusDef.AddMetaData({STREAM_LVL.Release, 1});
APD_Parameters_BusDef.AddMetaData({STREAM_LVL.Release, 1});

busElements = [ARECI_Parameters_BusDef; APRES_Parameters_BusDef; APD_Parameters_BusDef];

AN_Parameters_BusDef.AssignBusElements(busElements);


%% clear working variables

clear busElements
clear BusName
