flagCheckNameLength = true;

%% GEN_Parameters

SERVICE_Parameters_BusDef = BusParamDef("SERVICE_Parameters", "Descripton goes here");

busElements = [ ... 
    % signal name                   %dim    %datatype   % sample time   %    
    %% service mode signals
    BusSignalParamDef('s_ServiceModeCmd_enum'            ,   OMM_STATE.Off   ,   1   ,    'Enum: OMM_STATE',  -1,     'real', 'Sample','Fixed',  [],  [],    '',          '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('s_ServiceSleepTimerBreak_bool'    ,   0               ,   1   ,    'boolean',          -1,     'real', 'Sample','Fixed',  [],  [],    '',          '', {STREAM_LVL.Release, 1});...
    % Flush N2
    BusSignalParamDef('p_APRES_SP_Flush_p_bara'          ,   1.1             ,   1   ,    'single',           -1,     'real', 'Sample','Fixed',  [],  [],    '',          '', {STREAM_LVL.Release, 1});...      
    % Venting Thermal System
    BusSignalParamDef('p_STCL_TCV_VentOpen_pos_per'      ,   50              ,   1   ,    'single',           -1,     'real', 'Sample','Fixed',  [],  [],    'percent',          '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_TCV_MinVentOpen_pos_per'   ,   15              ,   1   ,    'single',           -1,     'real', 'Sample','Fixed',  [],  [],    'percent',          '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_TCV_MaxVentOpen_pos_per'   ,   85              ,   1   ,    'single',           -1,     'real', 'Sample','Fixed',  [],  [],    'percent',          '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_TCP_VentOmega_pos_per'     ,   60              ,   1   ,    'single',           -1,     'real', 'Sample','Fixed',  [],  [],    'percent',          '', {STREAM_LVL.Release, 1});...  
    BusSignalParamDef('p_STCL_auxTCP_VentOmega_pos_per'  ,   60              ,   1   ,    'single',           -1,     'real', 'Sample','Fixed',  [],  [],    'percent',          '', {STREAM_LVL.Release, 1});...  
    BusSignalParamDef('p_ECCL_ETCP_VentingOmega_pos_per' ,   60              ,   1   ,    'single',           -1,     'real', 'Sample','Fixed',  [],  [],    'percent',          '', {STREAM_LVL.Release, 1});...  
    % Hold Anode Pressure 
    BusSignalParamDef('p_APRES_SP_HoldPressure_bara'     ,   1.1             ,   1   ,    'single',           -1,     'real', 'Sample','Fixed',  [],  [],    'percent',          '', {STREAM_LVL.Release, 1});...  
    BusSignalParamDef('p_APRES_MaxMaintenancePres_bara'  ,   1.2             ,   1   ,    'single',           -1,     'real', 'Sample','Fixed',  [],  [],    'percent',          '', {STREAM_LVL.Release, 1});...  
    BusSignalParamDef('p_APRES_MinMaintenancePres_bara'  ,   0.8             ,   1   ,    'single',           -1,     'real', 'Sample','Fixed',  [],  [],    'percent',          '', {STREAM_LVL.Release, 1});...  
    %
    ];

SERVICE_Parameters_BusDef.AssignBusElements(busElements);

%% clear working variables

clear busElements
clear busName
