
%% TH_CtrlParam

STCL_Parameters_BusDef = BusParamDef("STCL_Parameters", "Description goes here");

p_STCL_SP_Oprtion_LUT_I_A       =   [   0    50   100   150   200   250   300   350   400   425   450   475   500];
p_STCL_SP_Oprtion_LUT_T_degC    =   [  58,   58,   62,   64,   66,   69,   72,   73,   76,   76,   76,   76,   76];
p_STCL_SP_Oprtion_LUT_dT_degC   =   [   2,    4,    6,    7,    8,    9,    8,    8,    8,    8,    8,    9,    9];

p_STCL_SPOut_Oprtion_LUT_T_degC    =   p_STCL_SP_Oprtion_LUT_T_degC + p_STCL_SP_Oprtion_LUT_dT_degC;

p_Emp_STCL_FFWD_LUT_I_A             =   [   0,  50,     100,    150,    200,    250,    300,    350,    400,    425,    450,    475,    500,    501];
p_Emp_STCL_FFWD_LUT_omega_rpm       =   [1100,  1100,   1100,   1100,   1280,   1460,   1640,   1930,   2280,   2400,   2500,   2600,   2700,   2800];
p_OversteerDynUp_LUT_omega_rpm      =   [0,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]; %[0,  0,   200,   500,   550,   550,   550,   550,   600,   600,   550,   550,   550,   550];
p_OversteerDynDown_LUT_omega_rpm    =   [0,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0];
p_OvSteerDynUp_TCV_LUT_pos_per      =   [0,  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]; %[0,  0,   10,   10,   15,   20,   20,   23,   25,   25,   25,   20,   20,   20];


p_STCL_auxTCP_LUT_I_A           =   [   0,  100,  250,  300,  350,  450,  500,  500,  500,  550,  510,  520,  530,  600];
p_STCL_auxTCP_LUT_omega_rpm     =   [2100, 2100, 2100, 2100, 2300, 2500, 2600, 2800, 3000, 3000, 3000, 3000, 3000, 3000];

p_TCV_LUT_OpeningPosition_per   =   [0,  2,   91,  95, 99, 100];
p_TCV_LUT_OpeningFlow_per       =   [5,  10,  70,  73, 80, 100];

p_TCV_MBC_mdl_weights           =   [   0.0737, -1.3695, -0.9171, 0.8643, -0.1963, -1.2959, -0.0762, -0.2792, 3.1358,  -0.7972];
p_TCV_MBC_mdl_u_norm            =   [1.0000    2.2363   39.5000   49.2000   45.4000    2.0370    2.1390    0.9320    1.0318    1.0484];
p_TCV_MBC_mdl_y_norm            =   93.6;

busElements = [ ... 
    % signal name                                   %dim    %datatype   % sample time   
    BusSignalParamDef('p_STCL_SP_Idle_TCV_opening_per'   ,   25                              , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'percentage',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_SP_Off_TCP_omega_rpm'      ,   0                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_SP_Off_auxTCP_omega_rpm'   ,   0                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_SP_EM_TCV_opening_per'     ,   80                              , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'percentage',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_SP_EM_TCP_omega_rpm'       ,   1600                            , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'K',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_SP_EM_auxTCP_omega_rpm'    ,   2100                            , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_SP_Mtc_TCV_opening_per'    ,   50                              , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'percentage',  '', {STREAM_LVL.Release, 1});...
    % controller parameters
    %BONTAZ TCV
    BusSignalParamDef('p_Btz_STCL_T_PID_P'               ,   2.5                             , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Btz_STCL_T_PID_I'               ,   0.35                            , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Btz_STCL_T_PID_D'               ,   0                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Btz_STCL_T_PID_N'               ,   1                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    %BELIMO TCV
    BusSignalParamDef('p_Blm_STCL_T_PID_P'               ,   6                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Blm_STCL_T_PID_I'               ,   0.06                            , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Blm_STCL_T_PID_D'               ,   0.4                             , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    %   
    BusSignalParamDef('p_Vlo_STCL_dT_PID_P'              ,   0                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Vlo_STCL_dT_PID_I'              ,   0                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Vlo_STCL_dT_PID_D'              ,   0                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    %
    BusSignalParamDef('p_Emp_STCL_dT_PID_P'              ,   0                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Emp_STCL_dT_PID_I'              ,   -2                              , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Emp_STCL_dT_PID_D'              ,   0                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Emp_STCL_dT_PID_N'              ,   1                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    %
    % feed forward pump parameters (EMP)
    BusSignalParamDef('p_Emp_STCL_FFWD_en_bool'          ,   true                            , 1,    'boolean',  -1,     'real', 'Sample','Fixed',  [],  [],    'seconds',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Emp_STCL_FFWD_Filter_PER_s'     ,   0                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'seconds',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Emp_STCL_FFWD_LUT_I_A'          ,   p_Emp_STCL_FFWD_LUT_I_A         , 14,   'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Emp_STCL_FFWD_LUT_omega_rpm'    ,   p_Emp_STCL_FFWD_LUT_omega_rpm   , 14,   'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_OversteerDynUp_LUT_omega_rpm'   ,   p_OversteerDynUp_LUT_omega_rpm,   14,   'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_OversteerDynDown_LUT_omega_rpm' ,   p_OversteerDynDown_LUT_omega_rpm, 14,   'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_OvSteerDynUp_TCV_LUT_pos_per'   ,   p_OvSteerDynUp_TCV_LUT_pos_per, 14,   'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'percentage',  '', {STREAM_LVL.Release, 1});...
    %ExtPumpLUT
    BusSignalParamDef('p_STCL_auxTCP_LUT_I_A'            ,   p_STCL_auxTCP_LUT_I_A           , 14,   'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_auxTCP_LUT_omega_rpm'      ,   p_STCL_auxTCP_LUT_omega_rpm     , 14,   'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    %
    BusSignalParamDef('p_STCL_dp_PID_P'                  ,   0                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_dp_PID_I'                  ,   0                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_dp_PID_D'                  ,   0                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    % feedback control setpoints
    BusSignalParamDef('p_STCL_SP_Oprtion_auxTCP_dp_bar'  ,   12                              , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bar',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_TH_Oprtion_auxTCP_dT_degC' ,   0.1                             , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'degC',  '', {STREAM_LVL.Release, 1});...
    % lookup tables 
    BusSignalParamDef('p_STCL_SP_Oprtion_LUT_I_A'        ,   p_STCL_SP_Oprtion_LUT_I_A       , 13,   'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_SP_Oprtion_LUT_T_degC'     ,   p_STCL_SP_Oprtion_LUT_T_degC    , 13,   'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'degC',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_SP_Oprtion_LUT_dT_degC'    ,   p_STCL_SP_Oprtion_LUT_dT_degC   , 13,   'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'degC',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_SPOut_Oprtion_LUT_T_degC'  ,   p_STCL_SPOut_Oprtion_LUT_T_degC , 13,   'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'degC',  '', {STREAM_LVL.Release, 1});...
    % actuator limits
    BusSignalParamDef('p_Vlo_TCP_min_rpm'                ,   2100                            , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Vlo_TCP_max_rpm'                ,   3900                            , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Emp_TCP_min_rpm'                ,   1300                            , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Emp_TCP_max_rpm'                ,   3300                            , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_auxTCP_min_rpm'                 ,   2100                            , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_auxTCP_max_rpm'                 ,   3000                            , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    %BONTAZ TCV
    BusSignalParamDef('p_Btz_TCV_min_opening_per'        ,   2                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'percentage',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Btz_TCV_max_opening_per'        ,   100                             , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'percentage',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_TCV_LUT_OpeningPosition_per'    ,   p_TCV_LUT_OpeningPosition_per   , 6,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'percentage',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_TCV_LUT_OpeningFlow_per'        ,   p_TCV_LUT_OpeningFlow_per       , 6,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'percentage',  '', {STREAM_LVL.Release, 1});...
    %BELIMO TCV
    BusSignalParamDef('p_Blm_TCV_min_opening_per'        ,   0                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'percentage',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Blm_TCV_max_opening_per'        ,   100                             , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'percentage',  '', {STREAM_LVL.Release, 1});...
    % signal filtering parameters
    BusSignalParamDef('p_Vlo_TCP_dT_Filter_TConstant_s'  ,   1                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'seconds',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Emp_TCP_dT_Filter_TConstant_s'  ,   0                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'seconds',  '', {STREAM_LVL.Release, 1});...
    %BONTAZ TCV
    BusSignalParamDef('p_Btz_TCV_T_Filter_TConstant_s'   ,   0.2                             , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'seconds',  '', {STREAM_LVL.Release, 1});...
    %BELIMO TCV
    BusSignalParamDef('p_Blm_TCV_T_Filter_TConstant_s'   ,   0                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'seconds',  '', {STREAM_LVL.Release, 1});...
    %MBC feedforward parameters (Btz only)
    % enabling
    BusSignalParamDef('p_TCV_MBC_en_VlvChar_bool'        ,   false                           , 1,    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_TCV_MBC_en_FFWDctrl_bool'       ,   false                           , 1,    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_TCV_MBC_en_dT_TCV_TH_degC'      ,   5                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_TCV_MBC_en_pos_TCV_TH_per'      ,   95                              , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_TCV_MBC_en_omega_TCP_TH_rpm'    ,   1000                            , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    % weights etc
    BusSignalParamDef('p_TCV_MBC_mdl_weights'            ,   p_TCV_MBC_mdl_weights           , 10,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_TCV_MBC_mdl_u_norm'             ,   p_TCV_MBC_mdl_u_norm            , 10,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_TCV_MBC_mdl_y_norm'             ,   p_TCV_MBC_mdl_y_norm            , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    % misc
    BusSignalParamDef('p_TCV_MBC_sat_upper'              ,   95                              , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_TCV_MBC_sat_lower'              ,   0                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_TCV_MBC_filt_T_s'               ,   0                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    % Deadtime for temperature difference calculation
    BusSignalParamDef('p_STCL_TDiff_DeadTime_D_s'        ,   1                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    % enable Tmix based control
    BusSignalParamDef('p_TCV_en_TMixCtrl_bool'           ,   false                           , 1,    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_TCV_TMixCtrl_Filt_T_s'          ,   2.0                             , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_TCV_TMixCtrl_extGain_I'         ,   0                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_OversteerDynUp_Hold_D_s'        ,   20                              , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'seconds',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_OversteerDynDown_Hold_D_s'      ,   10                              , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'seconds',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Oversteer_DecreaseTime'         ,   10                              , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'seconds',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_PressureDerating_Rate_rpm_s'     ,   0                              , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'rpm/s',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_PressureDerating_Hyst_p_bar'     ,   0.05                              , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    ];


STCL_Parameters_BusDef.AssignBusElements(busElements);

clear p_STCL_SP_Oprtion_LUT_I_A  p_STCL_SP_Oprtion_LUT_T_degC p_STCL_SP_Oprtion_LUT_dT_degC p_Emp_STCL_FFWD_LUT_I_A  p_Emp_STCL_FFWD_LUT_omega_rpm
clear p_STCL_auxTCP_LUT_I_A p_STCL_auxTCP_LUT_omega_rpm p_TCV_LUT_OpeningPosition_per p_TCV_LUT_OpeningFlow_per p_TCV_MBC_mdl_weights p_TCV_MBC_mdl_u_norm

%% TH_Thresholds

STCL_Logic_BusDef = BusParamDef("STCL_Logic", "Description goes here");

busElements = [ ... 
    % signal name                                   %dim    %datatype   % sample time   
    BusSignalParamDef('p_STCL_TCPOn_TH_omega_rpm'        ,   1000    , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_TCPOff_TH_omega_rpm'       ,   100     , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_TCPOn_TH_p_bara'           ,   1.2     , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_TCPOff_TH_p_bara'          ,   1.1     , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %
    BusSignalParamDef('p_STCL_AutoOff_T_degC'            ,   45      , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %
    BusSignalParamDef('p_STCL_StartingTCP_TO_s'          ,   100     , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    's',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_StoppingTCP_TO_s'          ,   100     , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    's',  '', {STREAM_LVL.Release, 1});...
    %OLDER: todo single check whether they are necessary
    % thresholds
    BusSignalParamDef('p_STCL_TCVOpen_TH_angle_deg'      ,   10      , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'deg',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_TCVClosed_TH_angle_deg'    ,   8       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'deg',  '', {STREAM_LVL.Release, 1});...
    % in check actuators currently used:  
    BusSignalParamDef('p_STCL_TCVinit_tol_angle_deg'     ,   6       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'deg',  '', {STREAM_LVL.Release, 1});...
    %
    BusSignalParamDef('p_STCL_auxTCPOn_TH_omega_rpm'     ,   1900    , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_auxTCPOff_TH_omega_rpm'    ,   1500    , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    % not needed currently: BusSignalParamDef('p_STCL_GeneralStart_MinPres_bara' , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    % not needed currently: BusSignalParamDef('p_STCL_GeneralOff_MaxPres_bara'   , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...    
    % not needed currently: BusSignalParamDef('p_STCL_TurnOnAuxTCP_TCP_TH_omega_rpm', 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'rpm',  '', {STREAM_LVL.Release, 1});...   
    % not needed currently: BusSignalParamDef('p_STCL_TurnOffAuxTCP_TCP_TH_omega_rpm', 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'rpm',  '', {STREAM_LVL.Release, 1});...
    %
    %BusSignalParamDef('p_STCL_TurnOffAuxTCP_TCV_TH_angle_deg', 20, 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'rpm',  '', {STREAM_LVL.Release, 1});...  
    % timings
    % not needed currently: BusSignalParamDef('p_STCL_GeneralStart_TO'           , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    's',  '', {STREAM_LVL.Release, 1});...
    % not needed currently: BusSignalParamDef('p_STCL_GeneralOff_TO'             , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    's',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_OpeningTCV_TO_s'           ,   100     , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    's',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_ClosingTCV_TO_s'           ,   100     , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    's',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_TT_TCVi_UseObserved_bool'  ,   false    , 1,    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_TT_CLSti_UseObserved_bool' ,   false    , 1,    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_TT_CLSto_UseObserved_bool' ,   false    , 1,    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_dT_SP_UseCLStiSet_bool'    ,   true    , 1,    'boolean',  -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...    
    %% deltaT Control Activation
    BusSignalParamDef('p_STCL_dT_CritActivation_bool'    ,   false    , 1,    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_dT_Crit_eLimits_T_degC'    ,   [-2 2]  , 2,    'single' ,   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_dT_Crit_ActiveTime_s'      ,   4       , 1,    'single' ,   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_Control_CLSti'             ,   1       , 1,    'boolean' ,   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_HeatingModeFeatActive'     ,   0       , 1,    'boolean' ,   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

STCL_Logic_BusDef.AssignBusElements(busElements);

%% STCL_Setpoints

STCL_Setpoints_BusDef = BusParamDef("STCL_Setpoints", "This bus holds the parameters regarding the setpoint generation");

busElements = [ ... 
    % signal name                                   %dim    %datatype   % sample time   
    BusSignalParamDef('p_STCL_SP_Mode'                      ,    TH_SP_MODE.PHASES3    , 1,    'Enum: TH_SP_MODE',   -1,     'real', 'Sample','Fixed',  [], [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_SPIncreaseRate_T_t'           ,   0.5    , 1,    'single',   -1,     'real', 'Sample','Fixed',  0,  100,    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_SPDecreaseRate_T_t'           ,   -0.6     , 1,    'single',   -1,     'real', 'Sample','Fixed', -100,  0,    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_SPIncreaseAccel_T_tt'         ,   0.015     , 1,    'single',   -1,     'real', 'Sample','Fixed',  0,  100,    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_SPIncreaseDecel_T_tt'         ,   -0.02     , 1,    'single',   -1,     'real', 'Sample','Fixed',  -100,  0,    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_SPDecreaseAccel_T_tt'         ,   -0.04   , 1,    'single',   -1,     'real', 'Sample','Fixed',  -100,  0,    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_STCL_SPDecreaseDecel_T_tt'         ,   0.015     , 1,    'single',   -1,     'real', 'Sample','Fixed',  0,  100,    'bara',  '', {STREAM_LVL.Release, 1});...
    ];

STCL_Setpoints_BusDef.AssignBusElements(busElements);


%% TH_Parameters

TH_Parameters_BusDef = BusParamDef("TH_Parameters", "Description goes here");

STCL_Parameters_BusDef.AddMetaData({STREAM_LVL.Release, 1});
STCL_Logic_BusDef.AddMetaData({STREAM_LVL.Release, 1});
STCL_Setpoints_BusDef.AddMetaData({STREAM_LVL.Release, 1});

busElements = [STCL_Parameters_BusDef, STCL_Logic_BusDef, STCL_Setpoints_BusDef];

TH_Parameters_BusDef.AssignBusElements(busElements);

%% clear working variables

clear busElements
clear busName
