flagCheckNameLength = true;
%load('Parameters\MassflowEstimator_Parameter_Hydrowell.mat')
%% EAC_Parameters

CAC_Parameters_BusDef = BusParamDef("CAC_Parameters", "Description goes here");

% Massflow Setpoint
p_EAC_SP_LUT_I_A                = [0    50    100    150    200    250    300    350    400    420    460    500    600];
p_EAC_SP_LUT_lambdaCT           = [5     5    2.7    2.5    2.3    2.1    2.0    1.8    1.6    1.6    1.6    1.6    1.6];

% Massflow Feed Forward Control
p_EAC_FFCurr_LUT_I_A            = [0    50     100      150     200     250     300     350     400     450];
p_EAC_FFCurr_LUT_omega_rpm      = [0  50000   50000   63000   76000   86000   95000   105000   109000   113000]; 
  
% Pressure Setpoint and Feed Forward Control
p_EAC_pCtrl_LUT_I_A             = [0    20    50    100    150    200    250    300    350    400    450    500];
p_EAC_pCtrl_SP_LUT_p_bara       = [1.15 1.15  1.25   1.35   1.65   1.85   2.10   2.15   2.15   2.25   2.25   2.25];
p_EAC_pCtrl_FFWD_LUT_pos_per    = [100  21    26     26     26     26     26     31     35    40      45    100];
p_EAC_Thrt_LL_LUT_pos_per       = [ 99  99    99     99     99     99     99     99     99     99     99     99];

% Compressor Surge Line
p_EAC_pCtrl_SPrt_LUT_mDot_gps   = [27.50 42.90 66.05 84.10 98.00 112.00 127.60];
p_EAC_pCtrl_SrgePrt_LUT_PR      = [1.2330 1.5605 2.079 2.432 2.632 2.865 3.165];

% Turbine Drain Valve
p_EAC_TurDrain_SP_LUT_I_A       = [0 45 100 150 200 250 300 350 400 420 460 500 600];
p_EAC_TurDrain_SP_LUT_period_s  = [60 60 60 60 60 60 60 60 60 60 60 60 60];
p_EAC_TurDrain_SP_LUT_open_s    = [0 0 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1];

busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_EAC_SP_Off_omega_rpm'           ,   0.0                             , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_SP_Idle_omega_rpm'          ,   40000                           , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_SP_provideExhst_omega_rpm'  ,   40000                           , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_SP_ConstRpm1_omega_rpm'     ,   40000                           , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_SP_ConstRpm2_omega_rpm'     ,   60000                           , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_SP_ConstMassflow1_mDot_gps' ,   30                              , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_SP_ConstMassflow2_mDot_gps' ,   30                              , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_SP_DryCathode_mDot_gps'     ,   40                              , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_upperRateLimit_rpmps'       ,   10000                           , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_lowerRateLimit_rpmps'       ,   -4000                           , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_settling_tol_gps'           ,   5                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_SP_Startup_lambda'          ,   5                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_SP_StartupTime_D_s'         ,   1                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_SP_LUT_I_A'                 ,   p_EAC_SP_LUT_I_A                , length(p_EAC_SP_LUT_I_A),   'single',    -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_SP_LUT_lambdaCT'            ,   p_EAC_SP_LUT_lambdaCT           , length(p_EAC_SP_LUT_lambdaCT),   'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_SP_DryCathode_omega_rpm'    ,   60000                           , 1,    'single',   -1,     'real', 'Sample','Fixed', [], [], '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_Shutdown_D_s'               ,   0.1                             , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_mDot_Filter_Window_s'       ,   1.7                             , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_SP_Mmax_percent'            ,   100                             , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
     % thresholds & limits
    BusSignalParamDef('p_EAC_OFF_MaxSpeed_TH_omega_rpm'  ,   1000                            , 1,    'single',   -1,     'real', 'Sample','Fixed',   [],     [],     '',     '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_ON_MinSpeed_TH_omega_rpm'   ,   3000                            , 1,    'single',   -1,     'real', 'Sample','Fixed',   [],     [],     '',     '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_ON_TurningOn_TO_s'          ,   5                               , 1,    'single',   -1,     'real', 'Sample','Fixed',   [],     [],     '',     '', {STREAM_LVL.Release, 1});...
    %% massflow control  
    BusSignalParamDef('p_EAC_PID_P'                      ,   700                             , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_PID_I'                      ,   400                             , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_PID_D'                      ,   0                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_PID_N'                      ,   1                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_PID_UpperLim_pos_per'       ,   103000                          , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_PID_LowerLim_pos_per'       ,   40000                           , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_FFCurr_LUT_I_A'             ,   p_EAC_FFCurr_LUT_I_A            , length(p_EAC_FFCurr_LUT_I_A),   'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_FFCurr_LUT_omega_rpm'       ,   p_EAC_FFCurr_LUT_omega_rpm      , length(p_EAC_FFCurr_LUT_omega_rpm),   'single',   -1,             'real', 'Sample','Fixed',    [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    %% pressure Control
    BusSignalParamDef('p_EAC_pCtrl_LUT_I_A'              ,   p_EAC_pCtrl_LUT_I_A             , length(p_EAC_pCtrl_LUT_I_A),    'single',    -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_Throt_SP_EM_pos_per'        ,   100                             , 1,    'single',   -1,     'real', 'Sample','Fixed',   [],     [],     '',     '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_Throt_SP_Idle_pos_per'        ,   100                             , 1,    'single',   -1,     'real', 'Sample','Fixed',   [],     [],     '',     '', {STREAM_LVL.Release, 1});...    
% enables
    BusSignalParamDef('p_EAC_pCtrl_en_FFWD'              ,   true                           , 1,    'boolean',   -1,     'real', 'Sample','Fixed',   [],     [],     '',     '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_pCtrl_en_Su1'               ,   true                           , 1,    'boolean',   -1,     'real', 'Sample','Fixed',   [],     [],     '',     '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_pCtrl_en_Su2'               ,   true                           , 1,    'boolean',   -1,     'real', 'Sample','Fixed',   [],     [],     '',     '', {STREAM_LVL.Release, 1});...
    % setpoints and feed forward
    BusSignalParamDef('p_EAC_pCtrl_SP_LUT_p_bara'        ,   p_EAC_pCtrl_SP_LUT_p_bara       , length(p_EAC_pCtrl_SP_LUT_p_bara),    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_pCtrl_FFWD_LUT_pos_per'     ,   p_EAC_pCtrl_FFWD_LUT_pos_per    , length(p_EAC_pCtrl_FFWD_LUT_pos_per),    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    % PID and limits
    BusSignalParamDef('p_EAC_pCtrl_PID_P'                ,   50                              , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_pCtrl_PID_I'                ,   30                              , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_pCtrl_PID_D'                ,   0                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_pCtrl_PID_N'                ,   1                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_pCtrl_PID_Offst_pos_per'    ,   100                             , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_pCtrl_PID_UL_pos_per'       ,   100                             , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_pCtrl_PID_LL_pos_per'       ,   p_EAC_Thrt_LL_LUT_pos_per       , length(p_EAC_Thrt_LL_LUT_pos_per),    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_pCtrl_PID_Filtr_T'          ,   1                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    % Surge Protection 1
    BusSignalParamDef('p_EAC_pCtrl_Su1_LUT_mDot_gps'     ,   p_EAC_pCtrl_SPrt_LUT_mDot_gps   , length(p_EAC_pCtrl_SPrt_LUT_mDot_gps),    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_pCtrl_Su1_LUT_PR'           ,   p_EAC_pCtrl_SrgePrt_LUT_PR      , length(p_EAC_pCtrl_SrgePrt_LUT_PR),    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_pCtrl_Su1_PR_factor'        ,   0.95                            , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_pCtrl_Su1_redSPGain'        ,   1.03                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_pCtrl_Su1_dbnce_s'          ,   0.05                            , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    % Surge Protection 2
    BusSignalParamDef('p_EAC_pCtrl_Su2_TH_Aps'           ,   20                              , 1,    'single',   -1,     'real', 'Sample','Fixed',   [],     [],     '',     '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_pCtrl_Su2_TH_rpmps'         ,   4000                            , 1,    'single',   -1,     'real', 'Sample','Fixed',   [],     [],     '',     '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_pCtrl_Su2_pos_per'          ,   5                               , 1,    'single',   -1,     'real', 'Sample','Fixed',   [],     [],     '',     '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_pCtrl_Su2_rate_UL'          ,   10                              , 1,    'single',   -1,     'real', 'Sample','Fixed',   [],     [],     '',     '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_pCtrl_Su2_rate_LL'          ,   -2                              , 1,    'single',   -1,     'real', 'Sample','Fixed',   [],     [],     '',     '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_pCtrl_SP_EM_pos_per'        ,   100                             , 1,    'single',   -1,     'real', 'Sample','Fixed',   [],     [],     '',     '', {STREAM_LVL.Release, 1});...
    % turbine drain valve control
    BusSignalParamDef('p_EAC_TurDrain_SP_LUT_I_A'        ,   p_EAC_TurDrain_SP_LUT_I_A       , length(p_EAC_TurDrain_SP_LUT_I_A),    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_TurDrain_SP_LUT_period_s'   ,   p_EAC_TurDrain_SP_LUT_period_s  , length(p_EAC_TurDrain_SP_LUT_period_s),    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_TurDrain_SP_LUT_open_s'     ,   p_EAC_TurDrain_SP_LUT_open_s    , length(p_EAC_TurDrain_SP_LUT_open_s),    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_TurDrain_EM_SP_pos_enum'    ,   DVLV_STATE.Open                 , 1,    'Enum: DVLV_STATE',    -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    % physical properties
    BusSignalParamDef('p_EAC_IsentrEfficiency'           ,   0.75                            , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    % legacy
    BusSignalParamDef('p_EAC_ETVctrl_enable_bool'        ,   0                               , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    %Massflow Estimator
    BusSignalParamDef('p_MFE_EAC_Param_dc_mm'        ,   0                    , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_MFE_EAC_Param_regparamC'        ,   zeros(1,11)         , 11,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_MFE_EAC_Param_sigmaC'        ,   0                , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_MFE_EAT_Param_regparamT'        ,   zeros(1,11)         , 11,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_MFE_EAT_Param_sigmaT'        ,   0                , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    ];

clear p_EAC_SP_LUT_I_A p_EAC_SP_LUT_lambdaCT p_EAC_FFCurr_LUT_I_A p_EAC_FFCurr_LUT_omega_rpm p_EAC_pCtrl_LUT_I_A p_EAC_pCtrl_SP_LUT_p_bara
clear p_EAC_pCtrl_FFWD_LUT_pos_per p_EAC_Thrt_LL_LUT_pos_per p_EAC_pCtrl_SPrt_LUT_mDot_gps p_EAC_pCtrl_SrgePrt_LUT_PR
clear p_EAC_TurDrain_SP_LUT_I_A p_EAC_TurDrain_SP_LUT_period_s p_EAC_TurDrain_SP_LUT_open_s

CAC_Parameters_BusDef.AssignBusElements(busElements);

%% AIRCL_Parameters

AIRCL_Parameters_BusDef = BusParamDef("AIRCL_Parameters", "Description goes here");

p_AIRCL_FFWD_LUT_Qdot_Watt  = [-7000  -6600 -5000 -3700 -3000 -2000 -1000 -999 0];
p_AIRCL_FFWD_LUT_pos_per    = [62     62    50    42    30    20    10    0    0];

busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_AIRCL_SP_Off_pos_percent'       ,   0                           , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_AIRCL_SP_On_T_degC'             ,   74                          , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    % AIRCL controller parameters
    BusSignalParamDef('p_AIRCL_PID_P'                    ,   4                           , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_AIRCL_PID_I'                    ,   0.2                         , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_AIRCL_PID_D'                    ,   0                           , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_AIRCL_PID_N'                    ,   1                           , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_AIRCL_PID_Activate_dT_K'        ,   0.0                         , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_AIRCL_PID_Deactivate_dT_K'      ,   -10.0                       , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_AIRCL_PID_Offset_pos_per'       ,   0                           , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_AIRCL_PID_UpperLim_pos_per'     ,   100                         , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_AIRCL_PID_LowerLim_pos_per'     ,   0                           , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    %Feed Forward Look up Table
    BusSignalParamDef('p_AIRCL_FFWD_Qdot_Filtr_PER_s'    ,   2.0                         , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_AIRCL_FFWD_LUT_Qdot_Watt'       ,   p_AIRCL_FFWD_LUT_Qdot_Watt  , 9,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_AIRCL_FFWD_LUT_pos_per'         ,   p_AIRCL_FFWD_LUT_pos_per  , 9,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    ];

clear p_AIRCL_FFWD_LUT_Qdot_Watt p_AIRCL_FFWD_LUT_pos_per   

AIRCL_Parameters_BusDef.AssignBusElements(busElements);


%% CSEP_Parameters

CSEP_Parameters_BusDef = BusParamDef("CSEP_Parameters", "Description goes here");


busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    %BusSignalParamDef('p_CSEP_SP_EMShutdown_dp_bar'          , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CSEP_CSIVOpen_TH_percent'   ,   50  ,   1   ,   'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CSEP_CSOVOpen_TH_percent'   ,   50  ,   1   ,   'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CSEP_CSIVClose_TH_percent'  ,   10  ,   1   ,   'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CSEP_CSOVClose_TH_percent'  ,   10  ,   1   ,   'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CSEP_ETVClose_TH_percent'   ,   10  ,   1   ,   'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CSEP_ETVOpen_TH_percent'    ,   10  ,   1   ,   'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CSEP_CathodeOpen_TO_s'      ,   10  ,   1   ,   'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CSEP_CathodeClose_TO_s'     ,   10  ,   1   ,   'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CSEP_EMCSIVClose_TO_s'      ,   3   ,   1   ,   'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1}); 
    ];

CSEP_Parameters_BusDef.AssignBusElements(busElements);


%% CStoBlV_Parameters



CStoBlV_Parameters_BusDef = BusParamDef("CStoBlV_Parameters", "Description goes here");


p_CStoBlV_LUT_I_A=            [    0,  50, 100, 150, 200, 250, 300, 350, 400, 425, 450, 475, 500];
p_CStoBlV_LUT_T_degC=         [   54,  58, 62, 75];
p_CStoBlV_LUT_pos_percent=    [   100,  100,  100,  100,  100,  100,  100,  100,  100,  100,  100,  100, 100;
                                  0,    0,   50,   50,   50,   50,   80,  100,  100,  100,  100,  100, 100;
                                  0,    0,    0,    0,    0,   35,   70,  100,  100,  100,  100,  100, 100;
                                  0,    0,    0,    0,    0,   35,   70,  100,  100,  100,  100,  100, 100]';

busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    %% Humidifier Bypass Lookup
    BusSignalParamDef('p_CStoBlV_LUT_I_A'                ,   p_CStoBlV_LUT_I_A           , 13        ,'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CStoBlV_LUT_T_degC'             ,   p_CStoBlV_LUT_T_degC        ,  4        ,'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_CStoBlV_LUT_pos_percent'       ,                , 13,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CStoBlV_LUT_pos_percent'        ,   p_CStoBlV_LUT_pos_percent   , [4, 13]   ,'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CStoBlV_I_A_Filtr_PER_s'        ,   0.5                         , 1         ,'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CStoBlV_max_pos_percent'        ,   100                         , 1          ,'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CStoBlV_min_pos_percent'        ,   0                           , 1         ,'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...    
    BusSignalParamDef('p_CStoBlV_rate_limit_percentpers' ,   20                          , 1         ,'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CStoBlV_SP_Default_pos_percent' ,   10                          , 1         ,'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CStoBlV_SP_EM_pos_percent'      ,   10                          , 1         ,'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

clear p_CStoBlV_LUT_I_A p_CStoBlV_LUT_T_degC p_CStoBlV_LUT_pos_percent p_CStoBlV_I_A_Filtr_PER_s

CStoBlV_Parameters_BusDef.AssignBusElements(busElements);

%% CHU_Parameters

CHU_Parameters_BusDef = BusParamDef("CHU_Parameters", "Description goes here");


p_CHUBVw_LUT_I_A            =   [   0   50  100 150 200 250 300 350 400 425 450 475 500];
p_CHUBVw_LUT_T_degC         =   [   54  58  62  75];
p_CHUBVw_LUT_pos_percent    =   [   100  100  100  100  100  100  100  100  100  100  100  100 100;
                                    100  100  100  100  100  100  100  100  100  100  100  100 100;
                                    100  100  100  100  100  100  100  100  100  100  100  100 100;
                                    100  100  100  100  100  100  100  100  100  100  100  100 100]';

p_CHUBVd_LUT_I_A            =   [    0  50 100 150 200 250 300 350 400 425 450 475 500];
p_CHUBVd_LUT_T_degC         =   [   54  58 62 75];
p_CHUBVd_LUT_pos_percent    =   [   100  100  100  100  100  100  100  100  100  100  100  100 100;
                                      0    0   50   50   50   50   80  100  100  100  100  100 100;
                                      0    0    0    0    0   35   70  100  100  100  100  100 100;
                                      0    0    0    0    0   35   70  100  100  100  100  100 100]';

busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    %% Humidifier Bypass Lookup
    BusSignalParamDef('p_CHU_UseDrySideVlv'              ,   0                           , 1         ,'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', 'For bool is HIGH, the dry side bypass valve is used', {STREAM_LVL.Release, 1});...}
    BusSignalParamDef('p_CHU_UseWetSideVlv'              ,   1                           , 1         ,'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', 'For bool is HIGH, the wet side bypass valve is used', {STREAM_LVL.Release, 1});...}
    BusSignalParamDef('p_CHUBVw_LUT_I_A'                 ,   p_CHUBVw_LUT_I_A            , 13        ,'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CHUBVw_LUT_T_degC'              ,   p_CHUBVw_LUT_T_degC         ,  4        ,'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CHUBVw_LUT_pos_percent'         ,   p_CHUBVw_LUT_pos_percent    , [4, 13]   ,'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CHUBVw_I_A_Filtr_PER_s'         ,   0.5                         , 1         ,'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CHUBVw_max_pos_percent'         ,   100                         , 1         ,'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CHUBVw_min_pos_percent'         ,   0                           , 1         ,'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...    
    BusSignalParamDef('p_CHUBVw_rate_limit_percent'      ,   20                          , 1         ,'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CHUBVw_SP_Default_pos_percent'  ,   10                          , 1         ,'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CHUBVw_SP_EM_pos_percent'       ,   10                          , 1         ,'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...    
    BusSignalParamDef('p_CHUBVd_LUT_I_A'                 ,   p_CHUBVd_LUT_I_A            , 13        ,'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CHUBVd_LUT_T_degC'              ,   p_CHUBVd_LUT_T_degC         , 4         ,'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CHUBVd_LUT_pos_percent'         ,   p_CHUBVd_LUT_pos_percent    , [4, 13]   ,'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CHUBVd_I_A_Filtr_PER_s'         ,   0.5                         , 1         ,'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CHUBVd_max_pos_percent'         ,   100                         , 1         ,'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CHUBVd_min_pos_percent'         ,   0                           , 1         ,'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...    
    BusSignalParamDef('p_CHUBVd_rate_limit_percent'      ,   20                          , 1         ,'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CHUBVd_SP_Default_pos_percent'  ,   10                          , 1         ,'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CHUBVd_SP_EM_pos_percent'       ,   10                          , 1         ,'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

clear p_CHUBVw_LUT_I_A p_CHUBVw_LUT_T_degC p_CHUBVw_LUT_pos_percent p_CHUBVd_LUT_I_A p_CHUBVd_LUT_T_degC p_CHUBVw_LUT_pos_percent

CHU_Parameters_BusDef.AssignBusElements(busElements);

%% Cathode_Characteristics
%compressorMapData = load("compressorMap.mat");
%turbineMapData = load("turbineMap.mat");
%load("reg_param_comp_Fischer.mat");

CatChar_Parameters_BusDef = BusParamDef("CatChar_Parameters", "Description goes here");


busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    BusSignalParamDef('p_FT_EAC_CompMap_omega_rpm_norm',         zeros(1,11), 11,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.All, 1});...
    BusSignalParamDef('p_FT_EAC_CompMap_pRatio_1',               zeros(1,11), 11,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.All, 1});...
    BusSignalParamDef('p_FT_EAC_CompMap_mDotCorr_gps',           zeros(11,11), [11, 11],    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.All, 1});...
    BusSignalParamDef('p_FT_mDotTSE_Map_basicCovar'              , 1         , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_FT_mDotTSE_Map_dynCovarGain'            , 0.1         , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_FT_mDotTSE_Map_noDyn_TH_rpm'            , 1000         , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_FT_mDotTSE_Map_dynCovFil_PER_s'         , 3         , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_FT_mDotTSE_Map_rpm_cutoff'              , 10000         , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_FT_mDotTSE_sens_covar'                  , 30         , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_FT_mDotTSE_check_devi_lim'              , 0.3         , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_FT_mDotTSE_check_devi_dbnc'             , 0.5         , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    % Prushkhupan
    BusSignalParamDef('p_FT_mDotTSE_ana_params'                  , zeros(1,11), 11,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.All, 1});...
    BusSignalParamDef('p_FT_mDotTSE_ana_d_c'                     , 50*10^-3         , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    % massflow sensor bias correction
    BusSignalParamDef('p_FT_mDotTSE_biasCorr_const'              , 0         , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_FT_mDotTSE_biasCorr_gain'               , 1         , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],   '', '', {STREAM_LVL.Release, 1});...
    ];

clear compressorMapData turbineMapData reg_param_comp_Fischer_Data

CatChar_Parameters_BusDef.AssignBusElements(busElements);

%% CAT_Parameters
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

CAT_Parameters_BusDef = BusParamDef("CAT_Parameters", "Description goes here");

CAC_Parameters_BusDef.AddMetaData({STREAM_LVL.Release, 1});
AIRCL_Parameters_BusDef.AddMetaData({STREAM_LVL.Release, 1}); 
CSEP_Parameters_BusDef.AddMetaData({STREAM_LVL.Release, 1}); 
CStoBlV_Parameters_BusDef.AddMetaData({STREAM_LVL.Release, 1}); 
CHU_Parameters_BusDef.AddMetaData({STREAM_LVL.Release, 1}); 
CatChar_Parameters_BusDef.AddMetaData({STREAM_LVL.Release, 1});

busElements = [CAC_Parameters_BusDef; AIRCL_Parameters_BusDef; CSEP_Parameters_BusDef; CStoBlV_Parameters_BusDef; CHU_Parameters_BusDef; CatChar_Parameters_BusDef];

CAT_Parameters_BusDef.AssignBusElements(busElements);

%% clear working variables

clear busElements
clear busName
