
%% Variant Config Bus Definition


variantConfig_BusDef = BusDef("variantConfig", "Descripton goes here");


busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %    
    BusSignalDef('auxTCP'       , 1,  'Enum: VARIANT_auxTCP',       -1,     'real', 'Sample','Fixed',   [], [],     '', '', {STREAM_LVL.Release, 1});...
    BusSignalDef('TCP'          , 1,  'Enum: VARIANT_TCP',          -1,     'real', 'Sample','Fixed',   [], [],     '', '', {STREAM_LVL.Release, 1});...
    BusSignalDef('ETCP'         , 1,  'Enum: VARIANT_ETCP',         -1,     'real', 'Sample','Fixed',   [], [],     '', '', {STREAM_LVL.Release, 1});...
    BusSignalDef('TCV'          , 1,  'Enum: VARIANT_TCV',          -1,     'real', 'Sample','Fixed',   [], [],     '', '', {STREAM_LVL.Release, 1});...
    BusSignalDef('TCVDirection' , 1,  'Enum: VARIANT_TCVDirection', -1,     'real', 'Sample','Fixed',   [], [],     '', '', {STREAM_LVL.Release, 1});...
    BusSignalDef('TCV2Direction', 1,  'Enum: VARIANT_TCVDirection', -1,     'real', 'Sample','Fixed',   [], [],     '', '', {STREAM_LVL.Release, 1});...
    BusSignalDef('EAC'          , 1,  'Enum: VARIANT_EAC',          -1,     'real', 'Sample','Fixed',   [], [],     '', '', {STREAM_LVL.Release, 1});...
    BusSignalDef('Anode'        , 1,  'Enum: VARIANT_Anode',        -1,     'real', 'Sample','Fixed',   [], [],     '', '', {STREAM_LVL.Release, 1});...
    ];

variantConfig_BusDef.AssignBusElements(busElements);

variantConfig_BusDef.GenerateRespectiveDatatypeStructures();
