flagCheckNameLength = true;

%% ANODE

%% SM_pSens_ASVi

SM_pSens_ASVi_BusDef = BusParamDef("SM_pSens_ASVi","Description goes here");


busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_ASVi_CAU_Limits_p_bar'  ,   [4.5, 8.2]  , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ASVi_WARN_Limits_p_bar'	,   [4.0, 8.7]  , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ASVi_CAU_Debouncing_s'  ,   0.05        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ASVi_WARN_Debouncing_s' ,   0.1         , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_ASVi_p_VM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_pSens_ASVi_BusDef.AssignBusElements(busElements);

%% SM_pSens_APRVi

SM_pSens_APRVi_BusDef = BusParamDef("SM_pSens_APRVi","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_APRVi_CAU_Limits_p_bar'     ,   [1.5 4.8]   , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRVi_WARN_Limits_p_bar'    ,   [1.5 4.8]   , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRVi_CAU_Debouncing_s'     ,   0.01        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRVi_WARN_Debouncing_s'    ,   0.7        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_APRVi_p_VM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_pSens_APRVi_BusDef.AssignBusElements(busElements);

%% SM_pSens_ASti

SM_pSens_ASti_BusDef = BusParamDef("SM_pSens_ASti","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_ASti_CAU_Limits_p_bar'  ,   [-10, 3.5]  , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ASti_WARN_Limits_p_bar' ,   [-10, 4.3]  , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ASti_CAU_Debouncing_s'  ,   0.05        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ASti_WARN_Debouncing_s' ,   0.05        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_ASti_p_VM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_pSens_ASti_BusDef.AssignBusElements(busElements);

%% SM_pSens_MemDiff

SM_pSens_MemDiff_BusDef = BusParamDef("SM_pSens_MemDiff","Description goes here");

busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_MemDiff_CAU_Limits_p_bar'   ,   [-0.1, 0.4] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_MemDiff_WARN_Limits_p_bar'  ,   [-0.2, 0.5] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_MemDiff_CAU_Debouncing_s'   ,   0.05        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_MemDiff_WARN_Debouncing_s'  ,   0.05        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_MemDiff_p_VM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_pSens_MemDiff_BusDef.AssignBusElements(busElements);

%% SM_TSens_ASVi

SM_TSens_ASVi_BusDef = BusParamDef("SM_TSens_ASVi","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_ASVi_CAU_Limits_T_degC'     ,   [7.0, 100.0]    , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ASVi_WARN_Limits_T_degC'    ,   [3.0, 100.0]    , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ASVi_T_CAU_Debouncing_s'    ,   0.05            , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ASVi_T_WARN_Debouncing_s'   ,   0.1             , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_ASVi_p_VM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_TSens_ASVi_BusDef.AssignBusElements(busElements);

%% SM_dpSens_EACi

SM_dpSens_APRV_BusDef = BusParamDef("SM_dpSens_APRV","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_APRV_CAU_Limits_dp_bar'     ,   [-10.0, 3.5]    , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRV_WARN_Limits_dp_bar'    ,   [-10.0, 4.0]    , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRV_CAU_Debouncing_s'      ,   0.05            , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_APRV_WARN_Debouncing_s'     ,   0.7             , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_ASVi_p_VM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_dpSens_APRV_BusDef.AssignBusElements(busElements);

%% SM_TSens_ARP

SM_TSens_ARP_BusDef = BusParamDef("SM_TSens_ARP","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_ARP_CAU_Limits_T_degC'      ,   [-100.0, 135.0] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ARP_WARNL1_Limits_T_degC'     ,   [-100.0, 140.0] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ARP_WARNL2_Limits_T_degC'     ,   [-200.0, 200.0] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ARP_T_CAU_Debouncing_s'     ,   0.05            , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ARP_T_WARNL1_Debouncing_s'    ,   3.0             , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ARP_T_WARNL2_Debouncing_s'    ,   100.0             , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_ASVi_p_VM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_TSens_ARP_BusDef.AssignBusElements(busElements);

%% SM_PSens_ARP

SM_PSens_ARP_BusDef = BusParamDef("SM_PSens_ARP","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_ARP_CAU_Limits_P_degC'      ,   [-1000, 650]    , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ARP_WARNL1_Limits_P_degC'     ,   [-1000, 690]    , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ARP_WARNL2_Limits_P_degC'     ,   [-1000, 1000]    , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ARP_P_CAU_Debouncing_s'     ,   0.05            , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ARP_P_WARNL1_Debouncing_s'    ,   3.0             , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ARP_P_WARNL2_Debouncing_s'    ,   100.0             , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_ASVi_p_VM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_PSens_ARP_BusDef.AssignBusElements(busElements);

%% CATHODE

%% SM_pSens_EACi

SM_pSens_EACi_BusDef = BusParamDef("SM_pSens_EACi","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_EACi_CAU_Limits_p_bar'      ,   [0.8, 10.0] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EACi_WARN_Limits_p_bar'     ,   [0.7, 10.0] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EACi_P_CAU_Debouncing_s'    ,   0.05        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EACi_P_WARN_Debouncing_s'   ,   0.1         , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_EACi_p_VM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_pSens_EACi_BusDef.AssignBusElements(busElements);

%% SM_TSens_EACi

SM_TSens_EACi_BusDef = BusParamDef("SM_TSens_EACi","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_EACi_CAU_Limits_T_degC'     ,   [-100.0, 40]    , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'degC',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EACi_WARN_Limits_T_degC'    ,   [-100.0, 45]    , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EACi_T_CAU_Debouncing_s'    ,   0.05            , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EACi_T_WARN_Debouncing_s'   ,   1.5             , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_EACi_T_VM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_TSens_EACi_BusDef.AssignBusElements(busElements);

%% SM_mdotSens_EACi

SM_mdotSens_EACi_BusDef = BusParamDef("SM_mdotSens_EACi","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_EACi_CAU_Limits_mDot_gps'       ,   [1.2, 100]  , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'gps',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EACi_WARN_Limits_mDot_gps'      ,   [1.2, 100]  , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EACi_mdot_CAU_Debouncing_s'     ,   0.01        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EACi_mdot_WARN_Debouncing_s'    ,   1.5        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EACi_mdot_enable_limits_TH_A'   ,   45          , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_EACi_mDot_VM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_mdotSens_EACi_BusDef.AssignBusElements(busElements);


%% SM_TSens_CHUi

SM_TSens_CHUi_BusDef = BusParamDef("SM_TSens_CHUi","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_CHUi_CAU_Limits_T_degC'     ,   [10, 85]    , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'degC',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CHUi_WARN_Limits_T_degC'    ,   [3, 90]     , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CHUi_T_CAU_Debouncing_s'    ,   0.05        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CHUi_T_WARN_Debouncing_s'   ,   3.0         , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_CHUi_p_StatesVM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_TSens_CHUi_BusDef.AssignBusElements(busElements);

%% SM_TSens_CSti

SM_TSens_CSti_BusDef = BusParamDef("SM_TSens_CSti","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_CSti_CAU_Limits_T_degC'     ,   [10, 85]    , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'degC',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CSti_WARN_Limits_T_degC'    ,   [3, 90]     , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CSti_T_CAU_Debouncing_s'    ,   0.05        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CSti_T_WARN_Debouncing_s'   ,   1.00        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_CSti_T_StatesVM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_TSens_CSti_BusDef.AssignBusElements(busElements);

%% SM_pSens_CSti

SM_pSens_CSti_BusDef = BusParamDef("SM_pSens_CSti","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_CSti_CAU_Limits_p_bar'      ,   [0.1, 2.8]  , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CSti_WARN_Limits_p_bar'     ,   [0.1, 3.0]  , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CSti_p_CAU_Debouncing_s'    ,   0.05        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CSti_p_WARN_Debouncing_s'   ,   0.05        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_CSti_p_StatesVM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_pSens_CSti_BusDef.AssignBusElements(busElements);

%% SM_ TSens_INV

SM_TSens_INV_BusDef = BusParamDef("SM_TSens_INV","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_INV_CAU_Limits_T_deg'   ,   [-100.0, 90]    , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'degC',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_INV_WARNL1_Limits_T_deg'  ,   [-100.0, 98]    , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_INV_WARNL2_Limits_T_deg'  ,   [-100.0, 500]    , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_INV_CAU_Debouncing_s'   ,   0.05            , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_INV_WARNL1_Debouncing_s'  ,   1.0             , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_INV_WARNL2_Debouncing_s'  ,   100.0             , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_INV_p_StatesVM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_TSens_INV_BusDef.AssignBusElements(busElements);

%% SM_Surge_EAC

SM_Surge_EAC_BusDef = BusParamDef("SM_Surge_EAC","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    BusSignalParamDef('p_EAC_CAU_Limits_Surge'           ,   [-10.0, 0.9]    , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'degC',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_WARNL1_Limits_Surge'        ,   [-10.0, 0.95]   , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_WARNL2_Limits_Surge'        ,   [-10.0, 1.0]    , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_Surge_CAU_Debouncing_s'     ,   0.5             , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});... %changed
    BusSignalParamDef('p_EAC_Surge_WARNL1_Debouncing_s'  ,   0.1             , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_Surge_WARNL2_Debouncing_s'  ,   0.05            , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    ];

SM_Surge_EAC_BusDef.AssignBusElements(busElements);

%% SM_ISens_EAC

SM_ISens_EAC_BusDef = BusParamDef("SM_ISens_EAC","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    BusSignalParamDef('p_EAC_CAU_Limits_I_A'         ,   [-100.0, 110.0] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'degC',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_WARNL1_Limits_I_A'        ,   [-100.0, 120.0] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_WARNL2_Limits_I_A'        ,   [-200.0, 200.0] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_I_CAU_Debouncing_s'     ,   0.05            , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_I_WARNL1_Debouncing_s'    ,   1.0             , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_I_WARNL2_Debouncing_s'    ,   100.0             , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    ];

SM_ISens_EAC_BusDef.AssignBusElements(busElements);

%% SM_USens_EAC

SM_USens_EAC_BusDef = BusParamDef("SM_USens_EAC","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    BusSignalParamDef('p_EAC_CAU_Limits_U_V'         ,   [320.0, 800.0]  , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'degC',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_WARN_Limits_U_V'        ,   [310.0, 810.0]  , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_U_CAU_Debouncing_s'     ,   0.05            , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_U_WARN_Debouncing_s'    ,   0.05            , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    ];

SM_USens_EAC_BusDef.AssignBusElements(busElements);

%% SM_omegaSens_EAC

SM_omegaSens_EAC_BusDef = BusParamDef("SM_omegaSens_EAC","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    BusSignalParamDef('p_EAC_CAU_Limits_omega_rpm'       ,   [-100, 100000]  , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'degC',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_WARNL1_Limits_omega_rpm'      ,   [-100, 104000]  , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_WARNL2_Limits_omega_rpm'      ,   [-100, 200000]  , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_omega_CAU_Debouncing_s'     ,   0.05            , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_omega_WARNL1_Debouncing_s'    ,   0.05            , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_omega_WARNL2_Debouncing_s'    ,   100.0            , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    ];

SM_omegaSens_EAC_BusDef.AssignBusElements(busElements);


%% SM_TMotorSens_EAC

SM_TMotorSens_EAC_BusDef = BusParamDef("SM_TMotorSens_EAC","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    BusSignalParamDef('p_EAC_CAU_Limits_TMotor_degC'     ,   [-100, 170] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'degC',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_WARNL1_Limits_TMotor_degC'    ,   [-100, 175] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_WARNL2_Limits_TMotor_degC'    ,   [-100, 300] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_TMotor_CAU_Debouncing_s'    ,   0.05        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_TMotor_WARNL1_Debouncing_s'   ,   1.0         , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_EAC_TMotor_WARNL2_Debouncing_s'   ,   100.0         , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    ];

SM_TMotorSens_EAC_BusDef.AssignBusElements(busElements);

%% THERMAL

%% SM_ pSens_ECL

SM_pSens_ECL_BusDef = BusParamDef("SM_pSens_ECL","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_ECL_CAU_Limits_p_bar'   ,   [1.15, 2.0]  , 2,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ECL_WARN_Limits_p_bar'  ,   [1.05, 2.4]  , 2,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ECL_CAU_Debouncing_s'   ,   0.05        , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_ECL_WARN_Debouncing_s'  ,   1.0         , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_ECL_p_StatesVM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_pSens_ECL_BusDef.AssignBusElements(busElements);

%% SM_TSens_CLSti

SM_TSens_CLSti_BusDef = BusParamDef("SM_TSens_CLSti","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_CLSti_CAU_Limits_T_degC'    ,  [10.0, 100.0]    , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'degC',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CLSti_WARN_Limits_T_degC'   ,  [3.0, 100.0]     , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CLSti_T_CAU_Debouncing_s'   ,   0.05            , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CLSti_T_WARN_Debouncing_s'  ,   3.0             , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_CLSti_T_StatesVM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_TSens_CLSti_BusDef.AssignBusElements(busElements);

%% SM_TSens_CLSto

SM_TSens_CLSto_BusDef = BusParamDef("SM_TSens_CLSto","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_CLSto_CAU_Limits_T_degC'  , [-100.0, 86.0]  , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'degC',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CLSto_WARN_Limits_T_degC' , [-100.0, 90.0]  , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CLSto_T_CAU_Debouncing_s' , 0.05            , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CLSto_T_WARN_Debouncing_s', 3.0             , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_CLSto_T_StatesVM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_TSens_CLSto_BusDef.AssignBusElements(busElements);

%% SM_pSens_CLSti

SM_pSens_CLSti_BusDef = BusParamDef("SM_pSens_CLSti","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_CLSti_CAU_Limits_p_bar'     ,   [1.2, 2.6]  , 2,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CLSti_WARN_Limits_p_bar'    ,   [1.1, 3.0] , 2,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CLSti_p_CAU_Debouncing_s'   ,   0.05        , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CLSti_p_WARN_Debouncing_s'  ,   0.05        , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_CLSti_p_StatesVM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_pSens_CLSti_BusDef.AssignBusElements(busElements);

%% SM_FCSDiff

SM_FCSDiff_BusDef = BusParamDef("SM_FCSDiff","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_FCSDiff_CAU_Limits_T_degC'  ,   [-99 , 15]   , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'degC',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_FCSDiff_WARN_Limits_T_degC' ,   [-100, 18]   , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_FCSDiff_T_CAU_Debouncing_s' ,   0.05        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_FCSDiff_T_WARN_Debouncing_s',   3           , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_FCSDiff_T_StatesVM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_FCSDiff_BusDef.AssignBusElements(busElements);

%% SM_pSens_CoolMemDiff

SM_pSens_CoolMemDiff_BusDef = BusParamDef("SM_pSens_CoolMemDiff","Description goes here");

busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_CoolMemDiff_CAU_Limits_p_bar'   ,   [-10.0, 1.3] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CoolMemDiff_WARN_Limits_p_bar'  ,   [-10.0, 1.5] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CoolMemDiff_CAU_Debouncing_s'   ,   0.05         , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CoolMemDiff_WARN_Debouncing_s'  ,   1.0          , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_MemDiff_p_VM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_pSens_CoolMemDiff_BusDef.AssignBusElements(busElements);

%% SM_pSens_TCPi

SM_pSens_TCPi_BusDef = BusParamDef("SM_pSens_TCPi","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    BusSignalParamDef('p_TCPi_CAU_Limits_p_bara'     ,   [0.95, 10.0]    , 2,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'degC',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_TCPi_WARN_Limits_p_bara'    ,   [0.82, 10.0]    , 2,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_TCPi_p_CAU_Debouncing_s'    ,   0.05            , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_TCPi_p_WARN_Debouncing_s'   ,   0.5             , 1,    'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    ];

SM_pSens_TCPi_BusDef.AssignBusElements(busElements);

%% ELECTRICAL

%% SM_USens_AvgCell

SM_USens_AvgCell_BusDef = BusParamDef("SM_USens_AvgCell","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_AvgCell_CAU_Limits_U_V'         ,   [0.5, 10.0] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'V',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_AvgCell_WARNL1_Limits_U_V'      ,   [0.2, 10.0] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_AvgCell_WARNL2_Limits_U_V'      ,   [0.2, 10.0] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_AvgCell_CAU_Debouncing_s'       ,   0.05        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_AvgCell_WARNL1_Debouncing_s'    ,   0.1         , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_AvgCell_WARNL2_Debouncing_s'    ,   0.05        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_AvgCell_U_StatesVM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_USens_AvgCell_BusDef.AssignBusElements(busElements);

%% SM_USens_AvgCell

busName = "SM_USens_AvgCell2";

SM_USens_AvgCell2_BusDef = BusParamDef("SM_USens_AvgCell2","Description goes here");

busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_AvgCell2_CAU_Limits_U_V'         ,   [0.5, 10.0] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'V',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_AvgCell2_WARNL1_Limits_U_V'      ,   [0.4, 10.0] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_AvgCell2_WARNL2_Limits_U_V'      ,   [0.4, 10.0] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_AvgCell2_CAU_Debouncing_s'       ,   0.05        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_AvgCell2_WARNL1_Debouncing_s'    ,   0.1         , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_AvgCell2_WARNL2_Debouncing_s'    ,   0.05        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %    BusSignalParamDef('p_AvgCell_U_StatesVM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_USens_AvgCell2_BusDef.AssignBusElements(busElements);

%% SM_USens_AvgCellMinCell

SM_USens_AvgCellMinCell_BusDef = BusParamDef("SM_USens_AvgCellMinCell","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_AvgCellMinCell_CAU_Limits_U_V'  ,   [-0.07, 0.07]   , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'V',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_AvgCellMinCell_WARN_Limits_U_V' ,   [-0.30, 0.30]   , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_AvgCellMinCell_CAU_Debcing_s'   ,   0.05            , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_AvgCellMinCell_WARN_Debcing_s'  ,   1.0             , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_AvgCellMinCell_U_StatesVM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_USens_AvgCellMinCell_BusDef.AssignBusElements(busElements);

%% SM_TSens_Shunt

SM_TSens_Shunt_BusDef = BusParamDef("SM_TSens_Shunt","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_Shunt_CAU_Limits_T_degC'    ,   [-100.0, 115.0] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'degC',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Shunt_WARN_Limits_T_degC'   ,   [-100.0, 120.0] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Shunt_T_CAU_Debouncing_s'   ,   0.05            , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Shunt_T_WARN_Debouncing_s'  ,   0.5             , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_Shunt_T_StatesVM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_TSens_Shunt_BusDef.AssignBusElements(busElements);

%% SM_ISens_Stack

SM_ISens_Stack_BusDef = BusParamDef("SM_ISens_Stack","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_Stack_CAU_Limits_I_A'       ,   [45, 430]   , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Stack_WARN_Limits_I_A'      ,   [20, 450]   , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Stack_I_CAU_Debouncing_s'   ,   0.05        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Stack_I_WARN_Debouncing_s'  ,   1.0         , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_Stack_I_StatesVM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_ISens_Stack_BusDef.AssignBusElements(busElements);

%% SM_USens_LVBus

SM_USens_LVBus_BusDef = BusParamDef("SM_USens_LVBus","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_LVBus_CAU_Limits_U_V'       ,   [16, 28]    , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'V',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_LVBus_WARN_Limits_U_V'      ,   [16, 28]    , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_LVBus_CAU_Debouncing_s'     ,   0.01        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_LVBus_WARN_Debouncing_s'    ,   0.15        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_LVBus_U_StatesVM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_USens_LVBus_BusDef.AssignBusElements(busElements);

%% SM_USens_HVBus

SM_USens_HVBus_BusDef = BusParamDef("SM_USens_HVBus","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_HVBus_CAU_Limits_U_V'       ,   [250, 800]  , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'V',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_HVBus_WARN_Limits_U_V'      ,   [250, 800]  , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_HVBus_CAU_Debouncing_s'     ,   0.01        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_HVBus_WARN_Debouncing_s'    ,   0.15        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_HVBus_U_StatesVM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_USens_HVBus_BusDef.AssignBusElements(busElements);

%% SM_RSens_IsoMonitor

SM_RSens_IsoMonitor_BusDef = BusParamDef("SM_RSens_IsoMonitor","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_IsoMonitor_CAU_Limits_R_Ohm'    ,   [50, 21000] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'Ohm',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_IsoMonitor_WARN_Limits_R_Ohm'   ,   [44, 21000] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_IsoMonitor_CAU_Debouncing_s'    ,   0.05        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_IsoMonitor_WARN_Debouncing_s'   ,   0.05        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_IsoMonitor_R_StatesVM_On_Bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_RSens_IsoMonitor_BusDef.AssignBusElements(busElements);

%% SM_ISens_DiffReqAct

SM_ISens_DiffReqAct_BusDef = BusParamDef("SM_ISens_DiffReqAct","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_DiffReqAct_CAU_Limits_I_A'      ,   [-15, 15]   , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_DiffReqAct_WARN_Limits_I_A'     ,   [-20, 20]   , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_DiffReqAct_I_CAU_Debouncing_s'	,     0.05        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_DiffReqAct_I_WARN_Debouncing_s' ,   10.0        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_Stack_I_StatesVM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_ISens_DiffReqAct_BusDef.AssignBusElements(busElements);

%% MISC

%% SM_H2Sens_SHORT

SM_H2Sens_Short_BusDef = BusParamDef("SM_H2Sens_Short","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_H2_CAU_Limits_H2_perLEL'    ,   [-1000, 25] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'ppm',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_H2_WARNL1_Limits_H2_perLEL' ,   [-1000, 45] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_H2_WARNL2_Limits_H2_perLEL' ,   [-1000, 45] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_H2_CAU_Debouncing_s'        ,   0.05        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_H2_WARNL1_Debouncing_s'     ,   0.5        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_H2_WARNL2_Debouncing_s'     ,   0.5         , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    ];

SM_H2Sens_Short_BusDef.AssignBusElements(busElements);

%% SM_H2Sens_LONG

SM_H2Sens_Long_BusDef = BusParamDef("SM_H2Sens_Long","Description goes here");

busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_H2LONG_CAU_Limits_H2_perLEL'    ,   [-1000, 25]     , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'ppm',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_H2LONG_WARNL1_Limits_H2_perLEL' ,   [-1000, 25]     , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_H2LONG_WARNL2_Limits_H2_perLEL' ,   [-1000, 1000]   , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_H2LONG_CAU_Debouncing_s'        ,   2.0             , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_H2LONG_WARNL1_Debouncing_s'     ,   2.0             , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_H2LONG_WARNL2_Debouncing_s'     ,   0.5             , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    ];

SM_H2Sens_Long_BusDef.AssignBusElements(busElements);

%% SM_H2Sens_HARD

SM_H2Sens_Hard_BusDef = BusParamDef("SM_H2Sens_Hard","Description goes here");

busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_H2HARD_CAU_Limits_H2_perLEL'    ,   [-1000, 25]     , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'ppm',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_H2HARD_WARNL1_Limits_H2_perLEL' ,   [-1000, 1000]     , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_H2HARD_WARNL2_Limits_H2_perLEL' ,   [-1000, 1000]   , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_H2HARD_CAU_Debouncing_s'        ,   2.0             , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_H2HARD_WARNL1_Debouncing_s'     ,   2.0             , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_H2HARD_WARNL2_Debouncing_s'     ,   0.5             , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    ];

SM_H2Sens_Hard_BusDef.AssignBusElements(busElements);


%% SM_ISens_Stack

SM_ISens_Imperm_BusDef = BusParamDef("SM_ISens_Imperm","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_Imperm_CAU_Limits_I_A',         [-0.5, 430] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'A',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Imperm_WARN_Limits_I_A',        [-0.5, 450] , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Imperm_I_CAU_Debouncing_s',     0.05        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_Imperm_I_WARN_Debouncing_s' ,   0.05        , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    ];

SM_ISens_Imperm_BusDef.AssignBusElements(busElements);

%% SM_TSens_CubeInside

SM_TSens_CubeInside_BusDef = BusParamDef("SM_TSens_CubeInside","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_CubInside_CAU_Limits_T_degC'    ,   [-100.0, 75]    , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'degC',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CubInside_WARN_Limits_T_degC'   ,   [-100.0, 80]    , 2,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CubInside_T_CAU_Debouncing_s'   ,   0.05            , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_CubInside_T_WARN_Debouncing_s'  ,   0.05            , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    'bara',  '', {STREAM_LVL.Release, 1});...
    %BusSignalParamDef('p_CubInside_T_StatesVM_On_bool'      , [2 4],    'boolean',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_TSens_CubeInside_BusDef.AssignBusElements(busElements);

%% SM_SensCheck

SM_SensCheck_BusDef = BusParamDef("SM_SensCheck","Description goes here");
busElements = [ ... 
    % signal name               %dim    %datatype   % sample time   %
    % setpoints
    BusSignalParamDef('p_SensCheck_pSens_Debouncing_s'   ,   0.5 , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_SensCheck_TSens_Debouncing_s'   ,   1.0 , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_SensCheck_CANComp_Debouncing_s' ,   1.0 , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_SensCheck_GEN_Debouncing_s'     ,   0.5 , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    BusSignalParamDef('p_SensCheck_UI_Debouncing_s'      ,   5   , 1,        'single',   -1,     'real', 'Sample','Fixed',  [],  [],    '',  '', {STREAM_LVL.Release, 1});...
    ];

SM_SensCheck_BusDef.AssignBusElements(busElements);

%% SM_Parameters

SM_Parameters_BusDef = BusParamDef("SM_Parameters","Description goes here");

SM_pSens_ASVi_BusDef.AddMetaData({STREAM_LVL.Release, 1});
SM_pSens_APRVi_BusDef.AddMetaData({STREAM_LVL.Release, 1});
SM_pSens_ASti_BusDef.AddMetaData({STREAM_LVL.Release, 1});
SM_pSens_MemDiff_BusDef.AddMetaData({STREAM_LVL.Release, 1});    
%new
SM_TSens_ASVi_BusDef.AddMetaData({STREAM_LVL.Release, 1}); 
SM_dpSens_APRV_BusDef.AddMetaData({STREAM_LVL.Release, 1});
SM_TSens_ARP_BusDef.AddMetaData({STREAM_LVL.Release, 1});  
SM_PSens_ARP_BusDef.AddMetaData({STREAM_LVL.Release, 1});  
% CATHODE
SM_pSens_EACi_BusDef.AddMetaData({STREAM_LVL.Release, 1}); 
SM_TSens_EACi_BusDef.AddMetaData({STREAM_LVL.Release, 1}); 
SM_mdotSens_EACi_BusDef.AddMetaData({STREAM_LVL.Release, 1});
SM_TSens_CHUi_BusDef.AddMetaData({STREAM_LVL.Release, 1});   
SM_TSens_CSti_BusDef.AddMetaData({STREAM_LVL.Release, 1});   
SM_pSens_CSti_BusDef.AddMetaData({STREAM_LVL.Release, 1});   
SM_TSens_INV_BusDef.AddMetaData({STREAM_LVL.Release, 1});
% new
SM_Surge_EAC_BusDef.AddMetaData({STREAM_LVL.Release, 1});    
SM_ISens_EAC_BusDef.AddMetaData({STREAM_LVL.Release, 1});    
SM_USens_EAC_BusDef.AddMetaData({STREAM_LVL.Release, 1});    
SM_omegaSens_EAC_BusDef.AddMetaData({STREAM_LVL.Release, 1});
SM_TMotorSens_EAC_BusDef.AddMetaData({STREAM_LVL.Release, 1});
% THERMAL
SM_pSens_ECL_BusDef.AddMetaData({STREAM_LVL.Release, 1});     
SM_TSens_CLSti_BusDef.AddMetaData({STREAM_LVL.Release, 1});   
SM_TSens_CLSto_BusDef.AddMetaData({STREAM_LVL.Release, 1});   
SM_pSens_CLSti_BusDef.AddMetaData({STREAM_LVL.Release, 1});   
SM_FCSDiff_BusDef.AddMetaData({STREAM_LVL.Release, 1});       
% new
SM_pSens_TCPi_BusDef.AddMetaData({STREAM_LVL.Release, 1});    
SM_pSens_CoolMemDiff_BusDef.AddMetaData({STREAM_LVL.Release, 1});
% ELECTRICAL
SM_USens_AvgCell_BusDef.AddMetaData({STREAM_LVL.Release, 1});
SM_USens_AvgCell2_BusDef.AddMetaData({STREAM_LVL.Release, 1});    
SM_USens_AvgCellMinCell_BusDef.AddMetaData({STREAM_LVL.Release, 1});
SM_TSens_Shunt_BusDef.AddMetaData({STREAM_LVL.Release, 1});      
SM_ISens_Stack_BusDef.AddMetaData({STREAM_LVL.Release, 1});      
SM_USens_LVBus_BusDef.AddMetaData({STREAM_LVL.Release, 1});      
SM_USens_HVBus_BusDef.AddMetaData({STREAM_LVL.Release, 1});      
SM_RSens_IsoMonitor_BusDef.AddMetaData({STREAM_LVL.Release, 1}); 
%new
SM_ISens_DiffReqAct_BusDef.AddMetaData({STREAM_LVL.Release, 1}); 
SM_ISens_Imperm_BusDef.AddMetaData({STREAM_LVL.Release, 1});     
% MISC
SM_H2Sens_Short_BusDef.AddMetaData({STREAM_LVL.Release, 1});     
SM_H2Sens_Long_BusDef.AddMetaData({STREAM_LVL.Release, 1});
SM_H2Sens_Hard_BusDef.AddMetaData({STREAM_LVL.Release, 1});      
SM_TSens_CubeInside_BusDef.AddMetaData({STREAM_LVL.Release, 1}); 
SM_SensCheck_BusDef.AddMetaData({STREAM_LVL.Release, 1}); 

busElements = [ ... 
    % ANODE
    SM_pSens_ASVi_BusDef;
    SM_pSens_APRVi_BusDef;
    SM_pSens_ASti_BusDef;
    SM_pSens_MemDiff_BusDef;    
    %new
    SM_TSens_ASVi_BusDef; 
    SM_dpSens_APRV_BusDef;
    SM_TSens_ARP_BusDef;  
    SM_PSens_ARP_BusDef;  
    % CATHODE
    SM_pSens_EACi_BusDef; 
    SM_TSens_EACi_BusDef; 
    SM_mdotSens_EACi_BusDef;
    SM_TSens_CHUi_BusDef;   
    SM_TSens_CSti_BusDef;   
    SM_pSens_CSti_BusDef;   
    SM_TSens_INV_BusDef;
    % new
    SM_Surge_EAC_BusDef;    
    SM_ISens_EAC_BusDef;    
    SM_USens_EAC_BusDef;    
    SM_omegaSens_EAC_BusDef;
    SM_TMotorSens_EAC_BusDef;
    % THERMAL
    SM_pSens_ECL_BusDef;     
    SM_TSens_CLSti_BusDef;   
    SM_TSens_CLSto_BusDef;   
    SM_pSens_CLSti_BusDef;   
    SM_FCSDiff_BusDef;       
    % new
    SM_pSens_TCPi_BusDef;    
    SM_pSens_CoolMemDiff_BusDef;
    % ELECTRICAL
    SM_USens_AvgCell_BusDef;
    SM_USens_AvgCell2_BusDef;    
    SM_USens_AvgCellMinCell_BusDef;
    SM_TSens_Shunt_BusDef;      
    SM_ISens_Stack_BusDef;      
    SM_USens_LVBus_BusDef;      
    SM_USens_HVBus_BusDef;      
    SM_RSens_IsoMonitor_BusDef; 
    %new
    SM_ISens_DiffReqAct_BusDef; 
    SM_ISens_Imperm_BusDef;     
    % MISC
    SM_H2Sens_Short_BusDef;     
    SM_H2Sens_Long_BusDef;
    SM_H2Sens_Hard_BusDef;      
    SM_TSens_CubeInside_BusDef; 
    SM_SensCheck_BusDef;        
    ];

SM_Parameters_BusDef.AssignBusElements(busElements);

%% clear working variables

clear busElements
clear busName
