import CoolProp.CoolProp as CP
from basic_physics import icao_atmosphere

class Turbine:
    def __init__(self, params_physics, isentropic_efficiency=0.85,
                 air_mass_flow_kg_s=1, pressure_in_Pa=1e5, temperature_in_K=80+273.15, flight_level_100ft=50,
                 nominal_BoP_pressure_drop_Pa=0.15*1e5, nominal_air_flow_kg_s=0.130):

        self.isentropic_efficiency = isentropic_efficiency
        self.params_physics = params_physics
        self.air_mass_flow_kg_s = air_mass_flow_kg_s
        self.pressure_in_Pa = pressure_in_Pa
        self.temperature_in_K = temperature_in_K
        self.flight_level_100ft = flight_level_100ft
        self.nominal_pressure_drop_Pa = nominal_BoP_pressure_drop_Pa
        self.nominal_air_flow_kg_s = nominal_air_flow_kg_s

    def calculate_power(self):
        """
        Calculate the mechanical power generated by the turbine.

        Args:
        - air_mass_flow_kg_s: The air mass flow rate in kg/s.
        - pressure_in_Pa: The inlet pressure in Pascals.
        - temperature_in_K: The inlet temperature in Kelvin.
        - pressure_out_Pa: The outlet pressure in Pascals.

        Returns:
        - turbine_power_W: The mechanical power generated by the turbine in Watts.
        """

        # Calculate the specific enthalpy at the inlet
        enthalpy_in_J_kg = CP.PropsSI('H', 'T', self.temperature_in_K, 'P', self.pressure_in_Pa, 'Air')

        # Evaluate the temperature and pressure at the given flight level
        temperature_out_K, pressure_out_Pa = icao_atmosphere(self.flight_level_100ft)

        # Calculate the specific enthalpy at the isentropic outlet
        enthalpy_out_J_kg = CP.PropsSI('H', 'T', temperature_out_K, 'P', pressure_out_Pa, 'Air')

        # Calculate the specific work output (isentropic work)
        specific_turbine_work_isentropic = enthalpy_in_J_kg - enthalpy_out_J_kg

        # Adjust for isentropic efficiency
        specific_turbine_work = specific_turbine_work_isentropic * self.isentropic_efficiency

        # Multiply by the flow rate to get the total power output
        turbine_power_W = specific_turbine_work * self.air_mass_flow_kg_s

        return turbine_power_W
    
    def calculate_BoP_pressure_drop(self, air_flow_kg_s: float)->float:
        """
        Calculate the pressure drop across the BoP components upstream the turbine for a given air mass flow rate.
        The "model" is a simple quadratic relationship between pressure drop and air mass flow rate.

        :param air_flow_kg_s: Air mass flow rate in [kg/s]
        :return: Pressure drop across the BoP components (cathode out -> turbine in) in [Pa]
        """

        pressure_drop_coefficient = self.nominal_pressure_drop_Pa / (self.nominal_air_flow_kg_s**2)
        pressure_drop_Pa = pressure_drop_coefficient * air_flow_kg_s**2

        return pressure_drop_Pa
    
# %% Example usage:
import parameters   
params_physics = parameters.Physical_Parameters() 
C1 = Turbine(params_physics, isentropic_efficiency=0.85)
            

#electrical power
power_el = C1.calculate_power()