classdef SENSOR < Simulink.IntEnumType
  enumeration
	None(0)
    ARP1_Sens(1)    
    ARP2_Sens(2)    	
    ASVi_pSens(3)    	
    APRVi_pSens(4)    	
    ASti_pSens(5)    	
    EAC_Sens(6)   	
    EACi_mDotSens(7) 
    EACi_pSens(8)  	
    EACo_pSens(9)    	
    CSti_pSens(10)    	
    EACi_TSens(11)    	
    CHUi_TSens(12)    	
    CSti_TSens(13)    	
    CSIV_Sens(14)    	
    CSOV_Sens(15)
    CHUBVd_Sens(16)
    CHUBVw_Sens(17)
    CStoBlV_Sens(18)    
    auxTCP_Sens(19)    	
    TCP_Sens(20)  	
    TCV_Sens(21)    	
    TCVi_pSens(22)
    TCPi_pSens(23)    	
    CLSti_pSens(24)    	
    TCVi_TSens(25)   	
    CLSti_TSens(26)    	
    CLSto_TSens(27)    	
    ETCP_Sens(28)    	
    ECL_pSens(29)    	
    CHXV_Sens(30)    	
    StCV_USens(31)    	
    IVT_Sens(32)   	
    BoP_ISens(33)    	
    IsoMon_RSens(34)
    Ambient_pSens(35)
    Ambient_TSens(36)
  end
    methods (Static = true)
     function retVal = addClassNameToEnumNames()
          retVal = true;
     end
end
end 