# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read



jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4


      # 2. Miniconda installieren
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9

      # 3. Conda-Umgebung erstellen und aktivieren
      - name: Create Conda Environment
        run: |
          conda config --set channel_priority flexible
          conda config --add channels conda-forge
          conda config --add channels defaults
          conda config --add channels https://repo.anaconda.com/pkgs/main
          conda config --add channels https://repo.anaconda.com/pkgs/r
          conda config --add channels https://repo.anaconda.com/pkgs/msys2
          conda env create -f ./05_overall/05_fcs_dimensioning_model/conda_env_pyFCS.yaml

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project

      - name: Run test Python file
        run: conda run -n conda_env_pyFCS python get_plots.py

      
